### ISSUE TITLE
Ressource to support VPC V3

### ISSUE THREAD

**Issue by mtbarka** [FlexibleEngineCloud/terraform-provider-flexibleengine#1009]
Hi,
There is no terraform ressource to support VPC API V3 for Flexible Engine.
Is it available on HWC , planned?
Thanks.

**Comment by ShiChangkuo** [comment]
@mtbarka can you give more details about what can we do with VPC API v3?

**Comment by mtbarka** [comment]
@ShiChangkuo , we want to allow customers to add public CIDR and private CIDR to a VPC using VPC API v3.

**Comment by Pseudodevincent** [comment]
Hello @ShiChangkuo the API v3 is described here: https://docs.prod-cloud-ocb.orange-business.com/api/vpc/vpc_apiv3_0001.html
It allows adding a secondary CIDR block to a VPC.
The secondary CIDR blocks allowed are described here : https://docs.prod-cloud-ocb.orange-business.com/usermanual/vpc/vpc_vpc_0007.html
cc @mtbarka

**Comment by ShiChangkuo** [comment]
got it! we will implement the V3 API in the next month.

**Comment by Pseudodevincent** [comment]
Thx !

**Comment by ShiChangkuo** [comment]
closed by #745
