### ISSUE TITLE
Fail to create lb_pool_v3 with version 1.43

### ISSUE THREAD

**Issue by gbrd** [FlexibleEngineCloud/terraform-provider-flexibleengine#1066]
Hi there,

### Terraform Version
Terraform version: 1.6.4

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_lb_pool_v3

### Terraform Configuration Files
```hcl
resource "flexibleengine_lb_pool_v3" "lb_pool_internet_443" {
  provider    = flexibleengine.fe_intdmz
  name        = "lb_pool_internet_443-${var.environment_slug}"
  lb_method   = "ROUND_ROBIN"
  protocol    = "TCP"
  listener_id = flexibleengine_lb_listener_v3.lb_listener_internet_443.id
  region      = data.vault_kv_secret_v2.fe.data.fe_region
}

```

### Debug Output
│ Error: error creating pool: Bad request with: [POST https://elb.eu-west-0.prod-cloud-ocb.orange-business.com/v3/06xxxxx/elb/pools], request_id: a9cyyyyb4d, error message: {"error_msg":"Unrecognized attribute(s) 'protection_status, protection_reason'","error_code":"ELB.8902","request_id":"a9cyyyyb4d"}
│ 
│   with flexibleengine_lb_pool_v3.lb_pool_internet_443,
│   on fe_networking_internet.tf line 44, in resource "flexibleengine_lb_pool_v3" "lb_pool_internet_443":
│   44: resource "flexibleengine_lb_pool_v3" "lb_pool_internet_443" {
│ 
╵
╷

### Expected Behavior
lb pool created
tf apply continue

### Actual Behavior
lb pool not created, tf apply stopped

### Steps to Reproduce
start from 0
1. `terraform apply`

- If I start from a previous state created with version 1.42 and just update to provider version 1.43 it work.
- If I start from zero 
  - => it fails with version 1.43, 
  - => it is ok with version 1.42 (with some warning of deprecated usage)

**Comment by ShiChangkuo** [comment]
@gbrd thanks for reporting on this issue! we will fix it soon.
