### ISSUE TITLE
Assign Fixed IP to RDS

### ISSUE THREAD

**Issue by dharmjit** [FlexibleEngineCloud/terraform-provider-flexibleengine#158]
Hi Team,

Is there a way to assign fixed IP to RDS. I checked the terraform flexible engine specifications, but you can only specify subnet information under this.

Thanks

**Comment by antonin-a** [comment]
Hello @dharmjit , 
This is not possible from user side to set the IP of RDS instance. 
As you can see on the documentation here : https://docs.prod-cloud-ocb.orange-business.com/en-us/usermanual/rds/en-us_topic_0046585334.html 
The Dynamic Host Configuration Protocol (DHCP) function must be enabled by default for subnets in which you plan to create RDS DB instances and cannot be disabled.

regards,

**Comment by dharmjit** [comment]
But in the UI, I can assign specific IP then why not in terraform. Is there a way to later update this using some other resource.

**Comment by antonin-a** [comment]
Hello @dharmjit , this feature is currently under deployment and not available through API at the moment. This will be available soon after API version upgrade, I will come back to you when I have more detailed information.

**Comment by bbenduduh** [comment]
Hello Team,

++ @dharmjit,
I had also noted this gap in the assignment of specifc IP to the RDS by Terraform.
And I was thinking about creating a bug about it.

Very useful feature for Terraform scripts!

**Comment by antonin-a** [comment]
Sorry for this long time without activity on this one... We are still waiting the APIs capability delivery, @DafuSHI can you give use an update?
Actual workaround is to use DNSaaS + private record based on RDS creation output (private IP), those steps can be done using Terraform (https://www.terraform.io/docs/providers/flexibleengine/r/dns_recordset_v2.html).

**Comment by antonin-a** [comment]
Hello @niuzhenguo , APIs are now available so we should be able to resolve this issues (which is currently the oldest one :) )
