### ISSUE TITLE
[CCE nodes] : node label not taken into account

### ISSUE THREAD

**Issue by Gwenael22** [FlexibleEngineCloud/terraform-provider-flexibleengine#183]
Hi there,

### Terraform Version
0.11.14

### Affected Resource(s)
- flexibleengine_cce_nodes_v3

### Expected Behavior
When i declare a label to a node, the label is present on the node in FE Console

### Actual Behavior
The label is not present on node in FE console. The label declared in Terraform template is not taken into account

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Template
````
resource "flexibleengine_cce_node_v3" "node_az_admin" {
  ...
  labels {
    admin-node = "true"
  }
  ...
````

**Comment by niuzhenguo** [comment]
@Gwenael22 Thanks for raising this, will test on my EVN to see.

**Comment by Gwenael22** [comment]
Hello,
Any updates about that problem ?
Thanks

**Comment by niuzhenguo** [comment]
@Gwenael22 It's true that the API also not resposne the labels, will dig more.

**Comment by niuzhenguo** [comment]
@Gwenael22 It's weird that he CCE node GET API doesn't response with the labels requested.

**Comment by niuzhenguo** [comment]
@Gwenael22 That should be an issue on CCE side, the labels with Create API seems not taken into account.

**Comment by Gwenael22** [comment]
Hi,
Thank you, @niuzhenguo 
Do you have a point of contact in CCE or FE API team to inform them of the issue or should i contact the Flexible Engine support team ?

**Comment by niuzhenguo** [comment]
@Gwenael22 Seems you should contact the support team.

**Comment by Gwenael22** [comment]
Ok, Thanks

**Comment by Gwenael22** [comment]
The FE support informs me that the feature is not available and that the documentation contains an error ...

**Comment by antonin-a** [comment]
@Gwenael22  and @niuzhenguo  I will push on Flexible Engine side to find a solution and ask for a fix. Sorry for the delay and inconvenience.

**Comment by Gwenael22** [comment]
Hello @antonin-a , any update concerning this issue ? Thanks

**Comment by antonin-a** [comment]
Hello @Gwenael22 , it is under progress to provide this capability. I will try to give you an expected delivery date by next week (waiting the feedback from our partner).

**Comment by Gwenael22** [comment]
Ok, thanks

**Comment by Gwenael22** [comment]
Hello @niuzhenguo, any news ?

**Comment by niuzhenguo** [comment]
@Gwenael22 We find a separated API for adding node labels, will have a try.

**Comment by Gwenael22** [comment]
Hello @niuzhenguo, any news please ? does this separated API permits to add labels on nodes ?

**Comment by niuzhenguo** [comment]
@Gwenael22 Seems we can't use k8s API separately.

**Comment by Gwenael22** [comment]
> 
> 
> Hello @Gwenael22 , it is under progress to provide this capability. I will try to give you an expected delivery date by next week (waiting the feedback from our partner).

Any news @antonin-a

**Comment by antonin-a** [comment]
Hello @Gwenael22, sorry for the delay. I just got the confirmation that it is planned for the next CCE upgrade planned by the end of November. I'll keep you updated if there is any change.

**Comment by Gwenael22** [comment]
Sad news :( particularly because the feature appears in the CCE API documentation ...

**Comment by antonin-a** [comment]
I know and I share your frustration. I will do my best to accelerate the delivery ...

**Comment by vlandemaine-orange** [comment]
@antonin-a  @niuzhenguo  Still does not working on January 2020
