### ISSUE TITLE
[OSS] Add default encryption during S3 bucket creation

### ISSUE THREAD

**Issue by Gwenael22** [FlexibleEngineCloud/terraform-provider-flexibleengine#252]
Hi there,
Is it possible to add default encryption to the OSS resource that permits to create a S3 bucket please ?
On API site, it seems that headers "x-amz-server-side-encryption" and "x-amz-server-side-encryption-aws-kms-key-id" permit to add this configuration to a bucket.
Thanks
Regards

**Comment by antonin-a** [comment]
Hello @Gwenael22, sorry for the delay. The service as been release on FE by the end of September (api and console side), we are currently working on it in order to provide this through FE TF provider

**Comment by niuzhenguo** [comment]
@Gwenael22 @antonin-a We can keep it as AWS provider is.

**Comment by antonin-a** [comment]
Hello @niuzhenguo do you have an update on this one ?

**Comment by niuzhenguo** [comment]
@antonin-a We just added obs_bucket resource with #318 , will add this support there. @ShiChangkuo please have a look at this, thanks!

**Comment by ShiChangkuo** [comment]
sorry for the delay, we can encryption an obs object with default master key after v1.12.0, please see [here](https://www.terraform.io/docs/providers/flexibleengine/r/obs_bucket_object.html#server-side-encryption-with-obs-default-master-key).

**Comment by antonin-a** [comment]
@ShiChangkuo @Gwenael22 can you confirm that we can close this one ?

**Comment by qukuijin1989** [comment]
hi @Gwenael22  can we close this one ?

**Comment by Gwenael22** [comment]
sorry @qukuijin1989, i can't answer you because I haven't worked on this subject for months

**Comment by qukuijin1989** [comment]
@Gwenael22  could you tell me who is working on this problem?
@ShiChangkuo  does this problem can beclosed?

**Comment by Gwenael22** [comment]
@qukuijin1989 no one, the project was canceled. the issue is opened since 1 year and months

**Comment by antonin-a** [comment]
@qukuijin1989 from my understanding its duplicate https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/419 and it is still not resolved. Regards,

**Comment by sbernier-corp** [comment]
Any news ?
My customer is waiting for this feature ;-)
