### ISSUE TITLE
[Feature request] Add the root ca for CCEv2 cluster creation

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#257]
Hello, 

With the new version of Kubernetes (1.13.7) available on CCEv2 coming the new feature for adding our own root certificate to the Kubernetes cluster on the creation step. This is a great feature, but this is not integrated with the Terraform provider. Can you add this functionnality to this Terraform provider?

### Terraform Version
0.12

### Affected Resource(s)
- flexibleengine_cce_cluster_v3

### Expected Behavior
Provide a root certificate when creating a CCEv2 cluster with Terraform

### Actual Behavior
We cannot provide a root certificate at the cluster creaton.

Regards, 

Valentin LANDEMAINE
Professional Services (OCB)

**Comment by antonin-a** [comment]
@DafuSHI , correct me if I'm wrong but it seems not available using the APIs neither. We should ask for it.

**Comment by DafuSHI** [comment]
Ok I will discuss this with the team tomorrow

**Comment by antonin-a** [comment]
@DafuSHI can you please update us ?
