### ISSUE TITLE
[OSS] Enable cross region replication in Terraform provider

### ISSUE THREAD

**Issue by vladimirBraquet** [FlexibleEngineCloud/terraform-provider-flexibleengine#296]
Cross-region replication in OSS in a great feature to ensure our backups (for instance) would survive a regions disaster.
It is currently possible to activate it thru the portal, but not thru Terraform

**Comment by antonin-a** [comment]
Hello @niuzhenguo, it would be really nice to have the capability to use OBS bucket cross region replication . I can't find it on the Huawei provider neither (https://www.terraform.io/docs/providers/huaweicloud/r/s3_bucket.html) did you know if it is something planned ? The API doc can be found here : https://docs.prod-cloud-ocb.orange-business.com/api/obs/en-us_topic_0175597490.html

**Comment by niuzhenguo** [comment]
@antonin-a In fact, we reuse AWS S3 resource for our OBS now, need to add new obs_bucket resource for this, will try to test our own API.

**Comment by qukuijin1989** [comment]
hi @niuzhenguo  does this feature has been released?
