### ISSUE TITLE
"Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by antonin-a** [FlexibleEngineCloud/terraform-provider-flexibleengine#299]
Hello,

I'm facing an issue with my Gtihub Actions Workflow that trigger a CCE cluster and nodes deployment (https://github.com/antonin-a/terraform-cce-actions/blob/master/.github/workflows/CCE_CI.yml), some of my runs are running without any issues but sometime it crash with a "Error: Provider produced inconsistent result after apply".

### Terraform Version
 0.12.20

### Affected Resource(s)
CCE cluster

### Terraform Configuration Files
https://github.com/antonin-a/terraform-cce-actions

### Expected Behavior
Apply running without issue. Ex: https://github.com/antonin-a/terraform-cce-actions/actions/runs/35464399

### Actual Behavior
Sometime it crash with the following error :
```
Error: Provider produced inconsistent result after apply

When applying changes to module.cce.flexibleengine_cce_cluster_v3.cce_cluster,
provider "registry.terraform.io/-/flexibleengine" produced an unexpected new
value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


##[error]Docker run failed with exit code 1 
```
Ex: https://github.com/antonin-a/terraform-cce-actions/actions/runs/35704104

### Steps to Reproduce
This one is unclear as it seems to happen radomly. My workflow is cron scheduled every 12h.

Thank you by advance for your help

**Comment by niuzhenguo** [comment]
@antonin-a Can you add TF_LOG=DEBUG and OS_DEBUG=true with the apply action to get more information about the issue?

**Comment by antonin-a** [comment]
Hello @niuzhenguo, thank you for your help. I've set TF_LOG and OS_DEBUG and I'll post the logs here next time the issue occurs (it happens almost twice a week with 2 deployment/day as your can see here: https://github.com/antonin-a/terraform-cce-actions/actions) .

**Comment by antonin-a** [comment]
Hello @niuzhenguo ,
```
This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/02/27 01:10:47 [ERROR] module.cce: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to module.cce.flexibleengine_cce_cluster_v3.cce_cluster, provider "registry.terraform.io/-/flexibleengine" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

Error: Provider produced inconsistent result after apply

When applying changes to module.cce.flexibleengine_cce_cluster_v3.cce_cluster,
provider "registry.terraform.io/-/flexibleengine" produced an unexpected new
value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

2020-02-27T01:10:47.522Z [DEBUG] plugin: plugin process exited: path=/github/workspace/.terraform/plugins/linux_amd64/terraform-provider-flexibleengine_v1.11.1_x4 pid=61
2020-02-27T01:10:47.522Z [DEBUG] plugin: plugin exited

**Comment by niuzhenguo** [comment]
@antonin-a I looked through the full log on your github action. The issue is because we got a 404 error when waiting for CCE cluster status become available. Possible reasons are:
* The cluster is deleted on the Console or in other way during creating.
* Some issues with the CCE server side.

**Comment by antonin-a** [comment]
Hello @niuzhenguo, I do confirm that I've not performed any action using console during creation. Do you think that I should open a ticket on platform side to check if it is related to CCE servers side ?

**Comment by niuzhenguo** [comment]
@antonin-a Yes, and you can provide the 404 error with the cluster ID to help them debug on the server side.

**Comment by qukuijin1989** [comment]
hi @antonin-a  does this issues has been resolved?

**Comment by antonin-a** [comment]
I do not manage to reproduce anymore, closing
