### ISSUE TITLE
[IAM] Feature request : Terraform FE provider to support IAM user groups and custom policies creation

### ISSUE THREAD

**Issue by mirceabostan** [FlexibleEngineCloud/terraform-provider-flexibleengine#329]
Hi there,

### Terraform Version
0.12.20

### Affected Resource(s)
IAM resources

### Important Factoids
Terraform FE provider to support IAM user groups and custom policies creation

**Comment by antonin-a** [comment]
@niuzhenguo this one is already integrated on Huawei provider and we have few project requirement, Do you think that we can add it quickly ?

**Comment by niuzhenguo** [comment]
@antonin-a https://github.com/terraform-providers/terraform-provider-flexibleengine/issues/214#issuecomment-572839420

**Comment by antonin-a** [comment]
@niuzhenguo https://github.com/terraform-providers/terraform-provider-flexibleengine/issues/214#issuecomment-606670215

**Comment by niuzhenguo** [comment]
@antonin-a IAM user groups is already  integrated on Huawei provider https://www.terraform.io/docs/providers/huaweicloud/r/identity_group_v3.html 
Regarding custom policies creation seems not, and I'm not sure if we have such API exposed.

**Comment by DafuSHI** [comment]
This is not anymore an API issue, please deliver in 715 version

**Comment by niuzhenguo** [comment]
@DafuSHI  Custom Policies  will not included in 715 release.

**Comment by fculpo** [comment]
Hi,

The flexibleengine_identity_role_v3 resource does not seem to accept the resource parameter, hence we cannot target policy to specific resource.

Example usecase: Allowing GetObject and PutObject on a specific OBS bucket.

**Comment by niuzhenguo** [comment]
@fculpo Yes, we need to wait for the ability available on the API side before we can add it to terraform. @antonin-a @DafuSHI

**Comment by antonin-a** [comment]
@niuzhenguo  are you sure that is it not available on APIs side ? It is described on the online help here : https://docs.prod-cloud-ocb.orange-business.com/api/iam/iam_02_0013.html
(Table 5)

**Comment by antonin-a** [comment]
We can consider this one "FE provider to support IAM user groups and custom policies creation" as Done. To discuss the specific point related to "ressource" parameter that is missing I suggest to use : #381
