### ISSUE TITLE
New Ressource - VPN Endpoint

### ISSUE THREAD

**Issue by antonin-a** [FlexibleEngineCloud/terraform-provider-flexibleengine#334]
Hi there,

As VPC Endpoint is now available on Beta mode, can we add the resource to the next provider release ? 

The online documentation is available here : https://docs.prod-cloud-ocb.orange-business.com/vpcep/index.html

Regards,

Antonin

**Comment by niuzhenguo** [comment]
@antonin-a Will try, but can't assure you that it could be in the next month release due to there are already many requests now.

**Comment by antonin-a** [comment]
Hello @niuzhenguo sure, no problem. I just saw that the resource does not exist on Huawei provider so it's probably more work than expected. There is no project urgency for now regarding this one.
Thanks a lot for your help !

**Comment by ShiChangkuo** [comment]
@antonin-a the VPC endpoint can be exported by #436 #438 #443 #444, and will be available in v1.18.0

**Comment by qukuijin1989** [comment]
hi @antonin-a , if this issues has been resolved could you close it ?
