### ISSUE TITLE
Need to Improve DCS Resources to hide useless id Info

### ISSUE THREAD

**Issue by DafuSHI** [FlexibleEngineCloud/terraform-provider-flexibleengine#340]
Hello,

The current DCS resources has some not user friendly input like product id, region id etc. It has no sens e for user. Can we create a new version of DCS to hide those info from user?

**Comment by DafuSHI** [comment]
https://docs.prod-cloud-ocb.orange-business.com/en-us/dcs/doc/download/pdf/dcs-api.pdf Page 18, project id、available_zones

**Comment by ShiChangkuo** [comment]
Hi, Dafu

`region` has been deprecated in many resources, user can ignore it.
It's not possible to hide `product_id` and `available_zones` fields, as they are required in [flexibleengine_dcs_instance_v1](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/dcs_instance_v1) which are also mandatory in the API.
