### ISSUE TITLE
[VPC] - Custom Route Table Management

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#383]
Hello

As a Terraform developer, I would like to create custom route tables with specific routes and associate desired subnet(s).
I would like something like :
- flexibleengine_custom_route_table : create the route table
- flexibleengine_custom_route_table_association : associate one or more subnet to a custom route table
- flexibleengine_custom_route_table_route : create a route into a given custom route table
Could it be possible to add these new resources for the next provider release ?

Thanks in advance
Olivier

**Comment by niuzhenguo** [comment]
@osaluden Seems we don't have such APIs exposed on Cloud side :(

**Comment by osaluden** [comment]
Hello @niuzhenguo , do you have some news regarding this issue? Is custom route table API in the roadmap ?
 Thank you for your help.

**Comment by niuzhenguo** [comment]
@antonin-a @DafuSHI do you have any news about this?

**Comment by DafuSHI** [comment]
It is implemented. Please add to Terraform resource:
https://docs.prod-cloud-ocb.orange-business.com/api/vpc/vpc_route_0001.html

**Comment by DafuSHI** [comment]
Sry it seems to be a mistake please ignore

**Comment by vlandemaine-orange** [comment]
Hello, 

@niuzhenguo @DafuSHI @ShiChangkuo Do you have any news about this ?

Regards,

Valentin LANDEMAINE (OCB/PS)

**Comment by antonin-a** [comment]
@Pseudodevincent may we ask your help regarding this feature, can you confirm that APIs has been delivered on Cloud side ?

**Comment by Pseudodevincent** [comment]
Hello @antonin-a @vlandemaine-orange @DafuSHI , this requirement has been tracked a long time ago with no progress so far.
I'm going to try to put this at the top of the pile through internal tools.

**Comment by sebbbastien** [comment]
Hi,

Any news one year later?

**Comment by Pseudodevincent** [comment]
Hello @sebbbastien , I keep pushing R&D to have this (I just did again today).

**Comment by Pseudodevincent** [comment]
Hello @sebbbastien, I can tell you we are progressing on this subject. We have now route table APIs available on FE and we are only missing API documentation.
@ShiChangkuo can you start working on Terraform provider update to support route table management with Huawei Cloud API documentation https://support.huaweicloud.com/intl/en-us/api-vpc/vpc_apiroutetab_0001.html ?

**Comment by ShiChangkuo** [comment]
@Pseudodevincent If APIs are ready, we will try to implement it in the next release.

**Comment by ShiChangkuo** [comment]
closed by #843
