### ISSUE TITLE
Set system timezone on RDS

### ISSUE THREAD

**Issue by mgodlewski** [FlexibleEngineCloud/terraform-provider-flexibleengine#389]
### Terraform Version
Terraform v0.12.13

### Affected Resource(s)
- rds_instance_v3

I can't see any option to set the timezone of rds at a system level. Can you add it to the terraform plugin ?

Regards

**Comment by niuzhenguo** [comment]
@mgodlewski Sorry for the delay response, will add a time_zone argument for `rds_instance_v3`
