### ISSUE TITLE
[CCE] - Node Pool Management

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#392]
Hi there,

As a Terraform developper I would to manage CCE Node Pool thanks to Terraform in order to fully automate CCE administration.
Thanks in advance for your feedback.

B.R.
Olivier

**Comment by niuzhenguo** [comment]
Do we have such API exposed on FlexibleEngine?

**Comment by ypilpre** [comment]
Seems that API for POST action on  nodepools is not exposed on CCEv2. Only GET is available.

`{
    "message": "API not found",
    "request_id": "a4d7603d-4d6c-4761-8e54-f61d5b77bd89"
}

Based on https://support.huaweicloud.com/en-us/api-cce/cce_02_0354.html`

**Comment by fculpo** [comment]
Hi, any news on this ?

A flexibleengine_cce_nodepools_vX would be a great enhancement.

**Comment by antonin-a** [comment]
Hello @fculpo , timing is good :) It is under deployment and should be ok by the end of the day !

**Comment by qukuijin1989** [comment]
hi @osaluden , if this problem has been resolved, could you please close it ?

**Comment by osaluden** [comment]
@qukuijin1989 yes it is solved, issue closed. Thank you for your help!
