### ISSUE TITLE
[CCE] - Agency Management

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#406]
Hi there,

As a Terraform developer, I would like to associate an Angency to my CCE nodes. This option is already available in the web console (advanced ECS settings in CCE node creation form).

Thanks in advance for your help.

Best Regards
Olivier Saluden

**Comment by ShiChangkuo** [comment]
@osaluden The function is missing in CCE node, we will try to implement this requirement as soon as we can.

**Comment by osaluden** [comment]
Thank you @ShiChangkuo !

**Comment by ShiChangkuo** [comment]
we can specifies the iam agency name as follow:

```
  extend_param = {
    agency_name = "your iam agency name"
  }
```
