### ISSUE TITLE
[ECS] - Agency Management

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#407]
Hi there,

As a Terraform developer, I would like to associate an Angency to my ECS machines. This option is already available in the web console (advanced ECS settings).

Thanks in advance for your help.

Best Regards
Olivier Saluden

**Comment by ShiChangkuo** [comment]
@osaluden sorry for late response. According to the [API documention](https://docs.prod-cloud-ocb.orange-business.com/api/ecs/en-us_topic_0167957246.html#EN-US_TOPIC_0167957246__section1574435185018), you can try to add `agency_name` into metadata block.

```
resource "flexibleengine_compute_instance_v2" "instance_1" {
  ...
  metadata = {
    agency_name = "your agency name"
  }
}

**Comment by osaluden** [comment]
Thank you for your feedback @ShiChangkuo , I will try as soon as I can and let you know.

**Comment by osaluden** [comment]
@ShiChangkuo I can confirm it works. Thank you for your help.
