### ISSUE TITLE
[IAM] - Agency type "Cloud service" Management

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#409]
Hi there,

As a Terraform developper, I would like to create an Agency the same way I would do to through the web console.
The current rpovider version does not seem to allow "Cloud Service" agency type but only "Common account" type for the "delegated_domain_name" parameter.

Thanks in advance for your help.

**Comment by niuzhenguo** [comment]
@osaluden Seems we don't have such API support on Cloud side.

**Comment by antonin-a** [comment]
Hello,
I just changed the issue title to clarify the point, I will check on Cloud Side if there is a way to provide  Agency Type "Cloud service" APIs.

Regards,

Antonin

CC. @DafuSHI

**Comment by antonin-a** [comment]
@DafuSHI @qukuijin1989 can you please check how to fix this on provider APIs side ?

**Comment by LIUhuan123456** [comment]
@antonin-a I am working on this, I submitted a requirement for API for the first step
