### ISSUE TITLE
SFS Turbo Standard Performance import/create issue

### ISSUE THREAD

**Issue by screwyy** [FlexibleEngineCloud/terraform-provider-flexibleengine#416]
Hi there,

I'm trying to create a SFS Turbo Standard or Performance but don't know the syntax where I can specify the name of the type.
Until now I used type "nfs" for ordinary SFS, What is the name of the type for standard and performance ?

### Terraform Version
Terraform v0.12.28
+ provider.flexibleengine v1.16.2

### Affected Resource(s)
flexibleengine_sfs_file_system_v2

### Terraform Configuration Files
```hcl
resource "flexibleengine_sfs_file_system_v2" "sfs_sftp" {
  size         = 100
  name         = "sfs_sftp"
  access_to    = var.vpc_tru
  access_level = "rw"
  description  = "blabla"

  metadata = {
    "type" = "nfs"
  }
}
```
I also tried to create from FE console the resource with Turbo Standard specs and import it in terraform but I'm not able import it even thou I'm doing it as per official terraform [documentation](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/sfs_file_system_v2#import)
```
quartz@tsmlmfetlsans01 ~/terraform/test (master)$ terraform import flexibleengine_sfs_file_system_v2 xxxxxxx-yyyyyyy-9841-e3fcf1b1b073

Error: Invalid address

  on <import-address> line 1:
   1: flexibleengine_sfs_file_system_v2

Resource specification must include a resource type and name.
For information on valid syntax, see:
https://www.terraform.io/docs/internals/resource-addressing.html
```

**Comment by antonin-a** [comment]
Hello @screwyy , the ressource you are looking for is available here : https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/sfs_turbo (not the same as standard SFS).

**Comment by screwyy** [comment]
ohhhh, thanks
