### ISSUE TITLE
OBS KMS encryption

### ISSUE THREAD

**Issue by fculpo** [FlexibleEngineCloud/terraform-provider-flexibleengine#419]
Hi,

Is there any way to enable OBS bucket default encryption with terraform ?
I can't find any parameter allowing passing kms information in flexibleengine_obs_bucket

**Comment by antonin-a** [comment]
Hello @fculpo , on platform side the API call is described here : https://docs.prod-cloud-ocb.orange-business.com/api/obs/en-us_topic_0190318905.html 
@niuzhenguo is the ressources already existing on terraform side ? If not, is it possible to add this one ?
Regards

**Comment by ShiChangkuo** [comment]
@fculpo you can encrypt an object with `encryption = true`.  please refer to the [example](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/obs_bucket_object#server-side-encryption-with-obs-default-master-key)

**Comment by fculpo** [comment]
I saw that possibility, but what I want is the possibility to enable default bucket encryption while creating it.

**Comment by ShiChangkuo** [comment]
due to the limitation of [SDK ](https://docs.prod-cloud-ocb.orange-business.com/sdk-python-devg/obs/en-us_topic_0142798495.html), only object encryption can be supported now.

@antonin-a maybe you can submit a requirement to OBS.

Note: the link above is python SDK as I can not find the Go SDK of OBS on the support docs, but I think both of them have the same functions.

**Comment by antonin-a** [comment]
ok @ShiChangkuo noted. @DafuSHI can you help us here ?

**Comment by qukuijin1989** [comment]
JIRA link :https://jira.corp.cloudwatt.com/browse/BIDFE-2228

**Comment by sbernier-corp** [comment]
Hi,

Any news ?
My customer is waiting for this feature ;-)

**Comment by sbernier-corp** [comment]
Well we raise the issue in January .. so now customer wants it asap ;-)

**Comment by ShiChangkuo** [comment]
@sbernier-corp we will release the feature before the end of June.

Also, you can try to build with #554 to check whether it meets the requirement.

**Comment by sbernier-corp** [comment]
@ShiChangkuo, perfect sounds good.
Just have the following issue https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/548 that avoid my customer to migrate to last version of the terraform provider.
Can the 548 issue be fixed also ?

**Comment by fculpo** [comment]
@niuzhenguo We get an Access Denied when trying to apply encryption through terraform

```
...
encryption = true
kms_key_id = flexibleengine_kms_key_v1.customer.id
...
```

```
│ Error: failed to enable default encryption of OBS bucket <REDACTED>: AccessDenied,
│  Reason: Access Denied
```

**Comment by fculpo** [comment]
We also see different key ids between OBS encryption key selection, and KMS page
