### ISSUE TITLE
flexibleengine_sfs_file_system_v2 host output is empty

### ISSUE THREAD

**Issue by fculpo** [FlexibleEngineCloud/terraform-provider-flexibleengine#420]
Hi,

The output host of flexibleengine_sfs_file_system_v2 is empty.

According to the resource documentation, it should return the hostname of nfs server (which I could then alias in a DNS private zone).

My current workaround to get this value is `split(":", flexibleengine_sfs_file_system_v2.this.export_location)[0]`

**Comment by antonin-a** [comment]
Hi @fculpo. First, thanks a lot for raising those issues ! 
@niuzhenguo can you check why the 'host' attribute is not exported on https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/sfs_file_system_v2 ? 

@fculpo depending on your initial requirement, a quick workaround could be to use SFS Turbo (a new SFS service with better and 'dedicated' performances) and use the 'export_location' on this one : https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/sfs_turbo

**Comment by antonin-a** [comment]
@niuzhenguo @ShiChangkuo any update ?

**Comment by ShiChangkuo** [comment]
@fculpo It seems to be an API issue as `host` was missing in API response, does the `export_location` works well?

**Comment by ShiChangkuo** [comment]
@fculpo After checking to the sfs R&D team, the `host` is an internal attribute whch is meaningless for users.
If you want to export the sfs, please using the [flexibleengine_sfs_access_rule_v2](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/sfs_access_rule_v2).

**Comment by qukuijin1989** [comment]
hi @fculpo  could you check it, if it resolved could you close it ?

**Comment by fculpo** [comment]
Hi,

This is not an export / acces rule issue.

I just want to get the hostname of the NFS server once my `flexibleengine_sfs_file_system_v2` is created.

According to `flexibleengine_sfs_file_system_v2` documentation, I could use these outputs:

- `export_location` - The address for accessing the shared file system.
- `host` - The host name of the shared file system -> this description fits exactly my need

I did manage to get the hostname via export_location but I need to do some string manipulation on it to get only the host part: `split(":", flexibleengine_sfs_file_system_v2.this.export_location)[0]`

Regarding host, it returns empty so I can't use it.

**Comment by ShiChangkuo** [comment]
@fculpo I get what you mean.

`export_location` already includes the sfs server host name which cannot be used alone, so I think the `host` is unnecessary.
did I miss something?

**Comment by ShiChangkuo** [comment]
@fculpo  I'm going to remove the `host` attribute as it is meaningless and always empty.
