### ISSUE TITLE
[IAM] getting custom policy from flexibleengine_identity_role_v3

### ISSUE THREAD

**Issue by nicolasalab** [FlexibleEngineCloud/terraform-provider-flexibleengine#422]
Following the assignment example here 

https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/identity_role_assignment_v3, 

I'd like to create an assignment using a custom role id but the data flexibleengine_identity_role_v3 doesn't seem to work with a custom role name (search query has no results.).

Is there a way to get a custom role id or can you make this possible from data flexibleengine_identity_role_v3 ?

**Comment by antonin-a** [comment]
@niuzhenguo can you please check this one ?

**Comment by niuzhenguo** [comment]
Seems we can add a new data source for custom policy, will be working on this after custom policy resources added.
