### ISSUE TITLE
[IAM] Cannot create agency with AKSK, works with user/passwd

### ISSUE THREAD

**Issue by fculpo** [FlexibleEngineCloud/terraform-provider-flexibleengine#426]
Hi,

Probably related to this issue: https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/370

I cannot create agency while using only AKSK, getting a "Identity - Agency: Action Forbidden".

This however works when providing Username/Password (of the same user than the AKSK one).

Is this a bug or some limitation ?

**Comment by LIUhuan123456** [comment]
Hello, could you please try to remove region, and replace authurl with a global authurl:iam.eu-west-0.prod-cloud-ocb.orange-business.com
If it does not work, could you please help attach the code and send to me, thanks

**Comment by qukuijin1989** [comment]
hi @fculpo  have you try to remove region, and replace authurl with a global authurl:iam.eu-west-0.prod-cloud-ocb.orange-business.com

**Comment by fculpo** [comment]
Provider version = *1.18.0*

This works (we provide OS_PASSWORD and OS_SECRET_KEY via env variables):

```
provider "flexibleengine" {
  access_key = local.OS_ACCESS_KEY
  domain_name = "redacted"
  user_name   = "redacted"
  auth_url    = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com"
}
```

This doesn't work (removing user_name and passing  OS_SECRET_KEY via env variable):

```
provider "flexibleengine" {
  access_key = local.OS_ACCESS_KEY
  domain_name = "redacted"
  auth_url    = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com"
}

flexibleengine_identity_agency_v3.sfs_access_kms: Refreshing state... [id=11ebe92a9ba846b9b242ff0c70f0a811]
flexibleengine_identity_agency_v3.evs_access_kms: Refreshing state... [id=f0401e17c7234e9093502e87e1e6c8a4]

Error: Identity-Agency: Action Forbidden
Error: Identity-Agency: Action Forbidden

```

**Comment by fculpo** [comment]
BTW documentation states:
"Note: It can not set tenant_name in provider "flexibleengine" when using this resource."

Well it perfectly works with or without tenant_name, as long as we provide username+password

**Comment by antonin-a** [comment]
@DafuSHI @qukuijin1989 , we have the exact same issue for user creation. We have tried with and without region. It is working fine with User/Password but NOK with AK/SK
@osaluden

**Comment by qukuijin1989** [comment]
hi @osaluden  
could describe the scenario of the auth? the @ShiChangkuo  will determine the how to fix it

**Comment by osaluden** [comment]
Hello @qukuijin1989 
IAM objects creation (user, group, custom roles ...) fails with the following environment variables: OS_ACCESS_KEY, OS_SECRET_KEY, OS_USER_DOMAIN_NAME
The error is : `Error creating FlexibleEngine user: Action Forbidden`

If I authenticate with OS_USERNAME, OS_PASSWORD and OS_USER_DOMAIN_NAME, it works.

So basically, AK/SK authentication does not seem to allow the IAM management.

**Comment by qukuijin1989** [comment]
ok @osaluden 
@ShiChangkuo  user doesn't need federation

**Comment by ShiChangkuo** [comment]
@fculpo @antonin-a @osaluden sorry for the late response.

I also encountered the same error with AK/SK authentication, the provider has send the API request, but got the `Action Forbidden` from IAM service. 

@qukuijin1989 please have a look at this, we need your help.

**Comment by ShiChangkuo** [comment]
@fculpo the issue was fixed by the cloud side, please try it again.

**Comment by ShiChangkuo** [comment]
@fculpo I'm going to close this issue because there are no updates for a long time.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
