### ISSUE TITLE
Tags unavailable on majority of TF resources

### ISSUE THREAD

**Issue by fculpo** [FlexibleEngineCloud/terraform-provider-flexibleengine#427]
Hello,

It seems impossible to manage mutable tags via terraform for a majority of resources, while doable directly in the console.
Other providers often implement a tags argument for this purpose.

Am I missing something ?

**Comment by ShiChangkuo** [comment]
@fculpo can you provide a list of resources that need to be tagged?

**Comment by osaluden** [comment]
@ShiChangkuo basicaly all the resources you can tag thanks to the web console (ECS, ELB, RDS, VPC, Subnet ...)
Thank you for you help.

**Comment by antonin-a** [comment]
Hello @ShiChangkuo , aligned with @osaluden  :)

**Comment by qukuijin1989** [comment]
https://jira.corp.cloudwatt.com/browse/BIDFE-2222

**Comment by ShiChangkuo** [comment]
@fculpo @antonin-a the following resources will support tags:

1. flexibleengine_as_group_v1
2. flexibleengine_blockstorage_volume_v2
3. flexibleengine_vpc_v1
4. flexibleengine_vpc_subnet_v1
5. flexibleengine_lb_loadbalancer_v2
6. flexibleengine_lb_listener_v2
7. flexibleengine_rds_instance_v3
8. flexibleengine_rds_read_replica_v3

**Comment by qukuijin1989** [comment]
hi @fculpo 
could  you describe the usage scenario of use tags? because some of cloud service need to confirm your requirement

**Comment by fculpo** [comment]
I'm not sure about what you expect from my side.

I just need the possibility to pass tags with terraform, which is currently
doable via the console.

I could for instance use tags for billing purpose, prod/stg segmentation,
etc.

**Comment by ShiChangkuo** [comment]
@fculpo will close this issue as many resources supported `tags` field and we will still work on this feature.

if you find tags is missing in the resource you needed, please feel free to create a new issue just like #519.
