### ISSUE TITLE
[CCE] - Enable to create Node Pool with 0 nodes

### ISSUE THREAD

**Issue by osaluden** [FlexibleEngineCloud/terraform-provider-flexibleengine#429]
Hi there,

Latest Terraform provide in use : 1.17.0
Terraform 0.13.5 binary.

When  `initial_node_count` is set to "0" (int) FE API answers the following:
Error: Error creating Flexibleengine Node Pool: Missing input for argument [InitialNodeCount]

Is it a bug or a feature ? :) (I want to create a 0 node node-pool in order to automatically provision node only if the deployment requires new node)

Thank you for your help.

**Comment by niuzhenguo** [comment]
@osaluden It's a bug, we will fix soon. @Jason-Zhang9309 please have a look at this ^

**Comment by osaluden** [comment]
Thank you @niuzhenguo  !
