### ISSUE TITLE
requirements flexibleengine_vpc_route_v2

### ISSUE THREAD

**Issue by FridMehdi** [FlexibleEngineCloud/terraform-provider-flexibleengine#430]
### Terraform Version
Terraform v0.14.3

### Provider Version
Terraform v1.17.0

### Affected Resource(s)
- VPC Routes  => flexibleengine_vpc_route_v2

### Requirements 
We are not able to create a route with diffrent type of var nextHop, the value of nexthop could be only "peering" ?
It is possible to have all values (Server, NIC, NAT, Virtual ips) ? or is a probleme with the api it self ?

**Comment by niuzhenguo** [comment]
It's a problem with the API itself.

**Comment by FridMehdi** [comment]
@niuzhenguo tyanks hwo is responsible for the api devs I think the other types are missing  is that true ?

**Comment by niuzhenguo** [comment]
@antonin-a @DafuSHI Please have a look at this request?

**Comment by sebbbastien** [comment]
Hi,

Any news two years later?

**Comment by ShiChangkuo** [comment]
please use [flexibleengine_vpc_route](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpc_route) which is available in v1.35.0+
