### ISSUE TITLE
Request : Add encryption on SFS Turbo

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#433]
Hello,

Related to the #418 we also need to configure encryption on SFS Turbo ressources. On the basic SFS resource we can configure this by adding parameters in the metadata, but in the SFS Turbo we cannot configure metadata.

### Terraform Version
Terraform v0.14.3

### Affected Resource(s)
flexibleengine_sfs_turbo

Regards,

**Comment by ShiChangkuo** [comment]
@vlandemaine-orange Thanks for raising this, we will implement the feature before the end of this month.

**Comment by osaluden** [comment]
Hello @ShiChangkuo , thank you for taking care of this case. The Huawei SDK SFS Turbo implements the Metadata feature https://github.com/huaweicloud/golangsdk/blob/master/openstack/sfs_turbo/v1/shares/requests.go
Should be doable in short time.

**Comment by osaluden** [comment]
@ShiChangkuo that's great, thank you for your prompt action!
