### ISSUE TITLE
DMS resource creation

### ISSUE THREAD

**Issue by rapheon** [FlexibleEngineCloud/terraform-provider-flexibleengine#447]
Hi there,

Is it possible to create resource for the DMS service ?

**Comment by qukuijin1989** [comment]
hi @niuzhenguo  could you please check this

**Comment by alpersid** [comment]
Hello,


Distributed Message Service ( Kafka ) can be deployed using "**flexibleengine_dcs_product_v1**"

Please have a look at [dcs product](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/data-sources/dcs_product_v1#engine):


```
data "flexibleengine_dcs_product_v1" "product1" {
  engine = "kafka"
  version = "1.1.0"
  instance_type = "cluster"
  partition_num = 300
  storage = 600
  storage_spec_code = "dcs.physical.storage.high"
}
```

**Comment by qukuijin1989** [comment]
@rapheon hi tony, is this ticket can be closed?

**Comment by antonin-a** [comment]
Hello @alpersid this is a datasource for DCS (Redis aaS) so I feel that it is a mistake on the documentation. @ShiChangkuo can you confirm this point ?

**Comment by ShiChangkuo** [comment]
Hi, guys
    I will implement these resources in v1.26.0.

**Comment by ShiChangkuo** [comment]
> Hello,
> 
> Distributed Message Service ( Kafka ) can be deployed using "**flexibleengine_dcs_product_v1**"
> 
> Please have a look at [dcs product](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/data-sources/dcs_product_v1#engine):
> 
> ```
> data "flexibleengine_dcs_product_v1" "product1" {
>   engine = "kafka"
>   version = "1.1.0"
>   instance_type = "cluster"
>   partition_num = 300
>   storage = 600
>   storage_spec_code = "dcs.physical.storage.high"
> }
> ```

@alpersid flexibleengine_dcs_product_v1 data source can not work, I will add a new data source for DMS Kafka service
