### ISSUE TITLE
[DNS]-DNSaaS - CAA records 

### ISSUE THREAD

**Issue by qukuijin1989** [FlexibleEngineCloud/terraform-provider-flexibleengine#450]
CAA record type seems to be available through APIs but neither from the console nor from Terraform.
@niuzhenguo 

BIDFE-2213

**Comment by ShiChangkuo** [comment]
@qukuijin1989 we already fix it by #440, and will be available in the next release.

**Comment by qukuijin1989** [comment]
@ShiChangkuo could you provider the next release date?

**Comment by ShiChangkuo** [comment]
@qukuijin1989 now you can test this feature in v1.18.0

**Comment by qukuijin1989** [comment]
done
