### ISSUE TITLE
KMS - key_id 

### ISSUE THREAD

**Issue by qukuijin1989** [FlexibleEngineCloud/terraform-provider-flexibleengine#452]
The variable "key_id" is not exported contrarily to what is stated in the documentation for "flexibleengine_kms_key_v1" resource
@niuzhenguo @ShiChangkuo

**Comment by ShiChangkuo** [comment]
Hi, can `id` meet your requirement?

**Comment by antonin-a** [comment]
@ShiChangkuo I think so. We need to fix the doc or the code ;)
