### ISSUE TITLE
add email/phone field to identity_user_v3 in order to be able to login into FE console

### ISSUE THREAD

**Issue by screwyy** [FlexibleEngineCloud/terraform-provider-flexibleengine#474]
Hi there,

### Terraform Version
v0.12.28

### Affected Resource(s)
- identity_user_v3

### Terraform Configuration Files
```hcl
https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/identity_user_v3
```

### Expected Behavior
What should have happened?

- Create a user and with it's password connect to FE console

### Actual Behavior
What actually happened?
```
Login authentication can be enabled only if a mobile number, email address, or virtual MFA device has been bound to the user.
```
but I'm unable to add email pr phone because the resource is not capable yet :)

**Comment by ShiChangkuo** [comment]
@antonin-a @DafuSHI I am working on this, but get a 403 error from the cloud side even using the full permissions account.

may need your help here.
