### ISSUE TITLE
Documentation VPC Endpoint Service `type` -> `protocol`

### ISSUE THREAD

**Issue by q-b** [FlexibleEngineCloud/terraform-provider-flexibleengine#479]
The [documentation for VPC Endpoint Service](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpcep_service#type) is wrong. UDP or TCP in port_mapping should be specified with the key `protocol` not `type`.

**Comment by ShiChangkuo** [comment]
sorry for the writing error, will fix it soon.
