### ISSUE TITLE
[VPC Endpoint Service] Doc: allow all domains

### ISSUE THREAD

**Issue by q-b** [FlexibleEngineCloud/terraform-provider-flexibleengine#494]
From the VPC Endpoint Service documentation [permissions argument](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpcep_service#permissions) description:

> _iam:domain::*_ allows all users to access the VPC endpoint service.

This should just be the wildcard `*` instead of the whole string: 

```
  # flexibleengine_vpcep_service.vpcep_service will be updated in-place
   ~ resource "flexibleengine_vpcep_service" "vpcep_service" {
        ...
       ~ permissions  = [
           + "iam:domain::*",

...

Error: Error adding permissions to VPC endpoint service ..., error message: {"error_code":"EndPoint.3002","error_msg":"Invalid permission."}
```

**Comment by ShiChangkuo** [comment]
@q-b thanks for raising this, we will test the issue and update the documentation.
