### ISSUE TITLE
[flexibleengine_vpcep_approval] does not work cross-project.

### ISSUE THREAD

**Issue by q-b** [FlexibleEngineCloud/terraform-provider-flexibleengine#495]
Provider version: 1.18.0

Description: `flexibleengine_vpcep_approval` does not work cross-project.

1. Get the VPC endpoint service status OK:
```
[DEBUG] FlexibleEngine Request URL: GET https://vpcep.eu-west-0.prod-cloud-ocb.orange-business.com/v1/<PROJECT_ID_1>/vpc-endpoint-services/<VPC_EP_SERVICE_ID>
...
[DEBUG] FlexibleEngine Response Code: 200
...
```

2. Accept the connection from the VPC endpoint service OK:
```
[DEBUG] FlexibleEngine Request URL: POST https://vpcep.eu-west-0.prod-cloud-ocb.orange-business.com/v1/<PROJECT_ID_1>/vpc-endpoint-services/<VPC_EP_SERVICE_ID>/connections/action
...
[DEBUG] FlexibleEngine Response Code: 200
...
```

3. Check if the VPC endpoint is in the accepted state KO:
```
[INFO] Waiting for VPC endpoint(<VPC_EP_ID>) to become accepted
[DEBUG] Waiting for state to become: [accepted]
[DEBUG] FlexibleEngine Request URL: GET https://vpcep.eu-west-0.prod-cloud-ocb.orange-business.com/v1/<PROJECT_ID_1>/vpc-endpoints/<VPC_EP_ID>
...
[DEBUG] FlexibleEngine Response Code: 404
...
[DEBUG] FlexibleEngine Response Body: {
[DEBUG]   "error_code": "EndPoint.0005",
[DEBUG]   "error_msg": "The requested resource does not exist."
[DEBUG] }
...
```

We can see that `<PROJECT_ID_1>` is used instead of `<PROJECT_ID_2>` where the endpoint belongs.

**Comment by antonin-a** [comment]
@niuzhenguo can you please check this one

**Comment by ShiChangkuo** [comment]
@q-b does vpc endpoint approval work cross-project by console?

**Comment by q-b** [comment]
@ShiChangkuo you can see from the logs that acceptation works. We end up with an approved connection in the web UI (and connectivity indeed appears to be ok).

The problem is in the finalization of the `terraform apply` command. The provider tries to ensure that the connection is OK but fails to do so (because it is looking for the VPC endpoint object in the wrong project). Since that step is unsuccessful, terraform fails.

**Comment by ShiChangkuo** [comment]
@q-b I see your point.
As the approved `vpc endpoint` can created by other projects or other domain accounts, we can not query the details. I will try another way to support cross-project.

**Comment by q-b** [comment]
When should we expect a new release with the fix included?
