### ISSUE TITLE
S3 Default Bucket Encryption

### ISSUE THREAD

**Issue by sbernier-corp** [FlexibleEngineCloud/terraform-provider-flexibleengine#503]
Hi there,

This is a feature request on flexibleengine_s3_bucket resource.

There is no way on the flexibleengine_s3_bucket  resource to Enable Default Server Side Encryption.

From documentation of flexible engine :
https://docs.prod-cloud-ocb.orange-business.com/api/obs/en-us_topic_0190318905.html
There is description of Put API to activate the default encryption on the target Bucket.
PUT /?encryption  HTTP/1.1
User-Agent: curl/7.29.0
Host: bucketname.obs.region.example.com
Accept: */*
Date: date 
Authorization: authorization string
Content-Length: length

<ServerSideEncryptionConfiguration>
    <Rule>
        <ApplyServerSideEncryptionByDefault>
            <SSEAlgorithm>kms</SSEAlgorithm>
            <KMSMasterKeyID>kmskeyid-value</KMSMasterKeyID>
        </ApplyServerSideEncryptionByDefault>
    </Rule>
</ServerSideEncryptionConfiguration>

Can this behavior be added to the flexibleengine_s3_bucket resource as it's done on the AWS provider for the aws_s3_bucket with the server_side_encryption_configuration ?
Documentation can be found here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#enable-default-server-side-encryption

This is requirement is a customer need.

Thank you for your help and your work,

Best regards,

**Comment by antonin-a** [comment]
@sbernier-corp can you confirm that it is duplicating https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/419 ?

**Comment by sbernier-corp** [comment]
yes it is.
