### ISSUE TITLE
[Feature Request] OBS Bucket replication

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#505]
Hello, 

Since it's possible to create **Cross-AZ OBS Bucket**, we have a parameter in the API **"x-amz-az-redundancy**" used to enable the replication.

We don't have any parameters on the Terraform provider to enable this on the **flexibleengine_s3_bucket**  and **flexibleengine_obs_bucket** resources.

It is possible to add a new parameter on the provider to enable the replication for the creation of new bucket?

Regards,

Valentin LANDEMAINE
OCB - Professional Services

**Comment by qukuijin1989** [comment]
@vlandemaine-orange  
we will analyse your requirement 
cc to @ShiChangkuo
