### ISSUE TITLE
[Flexible Engine ELB monitor] - terraform crashes if monitor type is HTTP

### ISSUE THREAD

**Issue by alpersid** [FlexibleEngineCloud/terraform-provider-flexibleengine#517]
Hi there,

### Terraform Version
Terraform v0.14.9

Tested with :
plugin.terraform-provider-flexibleengine_v1.19.0
plugin.terraform-provider-flexibleengine_v1.19.1 

### Affected Resource(s)
- flexibleengine_lb_monitor_v2

### Terraform Configuration Files
```hcl


resource "flexibleengine_lb_loadbalancer_v2" "ELB" {
  name          = "ELB"
  vip_subnet_id = flexibleengine_vpc_subnet_v1.subnet.subnet_id
}

resource "flexibleengine_lb_listener_v2" "elb_listener_" {
  name		= "ELB_HTTP"
  protocol	= "HTTP"
  protocol_port	= 9000
  loadbalancer_id = flexibleengine_lb_loadbalancer_v2.ELB.id
}

resource "flexibleengine_lb_pool_v2" "elb_pool_" {

  name        = "POOL"
  protocol    = "HTTP"
  lb_method   = "ROUND_ROBIN"
  listener_id = flexibleengine_lb_listener_v2.elb_listener_id

  persistence {
    
    type        = "APP_COOKIE"
    cookie_name = "JSESSIONID"
  }

}

resource "flexibleengine_lb_monitor_v2" "monitor_" {

  name        = "HTTP_monitor"
  pool_id     = flexibleengine_lb_pool_v2.elb_pool_.id
  type        = "HTTP"
  port        = "1080"
  url_path    = "/test"
  delay       = 5
  timeout     = 3
  max_retries = 3
}

```

### Expected Behavior
The ELB, Listener and Monitor to be created

### Actual Behavior
In TCP mode for Listener, Pool and Monitor everything if working as expected.
If we create a new HTTP Listener on which we attach a HTTP POOL and a HTTP Monitor, terraform crashes at the Monitor creation.

module.networking.flexibleengine_lb_monitor_v2.monitor_: Still creating... [10s elapsed]
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Unavailable desc = transport is closing
Error: rpc error: code = Canceled desc = context canceled
Error: rpc error: code = Canceled desc = context canceled
panic: runtime error: invalid memory address or nil pointer dereference
2021-04-07T13:17:19.900Z [DEBUG] plugin.terraform-provider-flexibleengine_v1.19.0: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1121260]
2021-04-07T13:17:19.900Z [DEBUG] plugin.terraform-provider-flexibleengine_v1.19.0: 
2021-04-07T13:17:19.900Z [DEBUG] plugin.terraform-provider-flexibleengine_v1.19.0: goroutine 4776 [running]:
2021-04-07T13:17:19.900Z [DEBUG] plugin.terraform-provider-flexibleengine_v1.19.0: github.com/terraform-providers/terraform-provider-flexibleengine/flexibleengine.resourceMonitorV2Create(0xc00039d110, 0x1524300, 0xc00015eb00, 0x2, 0x224fea0)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Same issues were encountered on OpenStack and were finally fixed.
- [ Resolve LBaaS monitor crashing Terraform #102](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/98)
- [crash trying to create an openstack_lb_monitor_v2 #98](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/98)

**Comment by ShiChangkuo** [comment]
@alpersid thanks for raising this, will fix it soon.
