### ISSUE TITLE
[cce node pools] tags not available on cce module

### ISSUE THREAD

**Issue by fallmor** [FlexibleEngineCloud/terraform-provider-flexibleengine#519]
For billing purpose we need to tag resources deployed with cce node pools. From the console we can add tag manually on node pools but the terraform ressource does not support tagging. Are you planning to add this functionnality ?

**Affected Resource(s)**
resource_flexibleengine_cce_node_pool

Thanks in advance for your feedback.

**Comment by qukuijin1989** [comment]
@fallmor 
we will delivery this feature at 530
cc to @shichangk
