### ISSUE TITLE
[Feature Evolution] - add agency selection for AS Group / ECS

### ISSUE THREAD

**Issue by alpersid** [FlexibleEngineCloud/terraform-provider-flexibleengine#521]
Hello guys,

Currently there is an option to configure an agent on an ECS which will gather metrics from it.
 You will be able to see the metrics on Cloud Eye / Server Monitoring / Elastic Cloud Server.
I have the ICAgent already installed on the ECS by using a custom image.

Currently, if you want to configure it from terraform, there's no possibility to assign an agency to an ECS or to an AS Group.
In my current deployment I'm using  autoscaling, and in order to use ECS Monitoring with ICAgent I need to manually go to each instance (ECS) in the GUI and configure the agency manually.
If the as group will scale ( up or down ) I will need to perform the same action to the new resource.

The requirement is to have a way to configure the ICAgent agency for an AS Group or AS Configuration.

**Comment by ShiChangkuo** [comment]
Hi, @alpersid

Looks similar to #407, you can configure the agency by `metadata` field.

**Comment by alpersid** [comment]
I confirm that using metadata on as_configuration is working.

Thank you for your quick reaction!

**Comment by alpersid** [comment]
Thank you for your quick response!
I confirm that adding the field on as_configuration is working.
Duplicate of #
