### ISSUE TITLE
[AS Group] - elb limit

### ISSUE THREAD

**Issue by alpersid** [FlexibleEngineCloud/terraform-provider-flexibleengine#524]
Hello guys,

The AS Group is limited to only 3 ELBs. In my current deployment I plan to have > 8 ELBs for a single AS Group.
Can you change the limitation to > 10 ELBs?

'''
lbaas_listeners - (Optional) An array of one or more enhanced load balancer. The system supports the binding of up to **three load balancers**. The field is alternative to lb_listener_id. The lbaas_listeners object structure is documented below.
'''

### Terraform Version
13,14,15
### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_as_group_v1

Thank you in advance,
Alex

**Comment by alpersid** [comment]
Hello guys,
Can you please check this issue?
Thank you in advance,
Alex

**Comment by qukuijin1989** [comment]
@ShiChangkuo

**Comment by ShiChangkuo** [comment]
@alpersid Perhaps it's the limitation of AS Group service. You can submit a service ticket to report it.

**Comment by alpersid** [comment]
Hello guys,
I've opened a service ticket last week and I'm waiting for their feedback.
I will close this thread after I'll get the response, maybe it will help others ;)

**Comment by ShiChangkuo** [comment]
@alpersid Are there any updates?

**Comment by alpersid** [comment]
Hello,

Sorry for the late reply.
The response from the support teams:

`The change has been applied and now up to **six load balancers** can be added to an AS group (check attached)` 

However, I've found another limitation, **only 6 listeners** can be added to a AS Group.

I've requested also to increase the limit to >10 and the response is the following:

```
Kindly note that as per vendor confirmation, the current architecture of AS service supports the binding of up to **six load balancer listeners only** (Current Service Limitation)
We will consider upgrading AS service to expand its limitation (expected time is not clear yet)
```

So, it's up to you to increase the limit of listeners :)

Can you help me with this request ?

Thank you in advance,

Alex

**Comment by ShiChangkuo** [comment]
Actually, the limitation is only stated in the docs. It has no limitation in the code, because the specifications can be changed by the cloud side.

I will update the docs later.

**Comment by alpersid** [comment]
The limitation now its configured to max 6 load balancer and max 6 listeners. How can we proceed to have more then 10 loadbalancers and more then 10 listeners for the same as_group?
Thanks
