### ISSUE TITLE
[Product Evolution][AS Group][Lifecycle hook] - add lifecycle hook

### ISSUE THREAD

**Issue by alpersid** [FlexibleEngineCloud/terraform-provider-flexibleengine#525]
Hello guys,

I would like you to add the management of the resource "lifecycle_hooks" using terraform

The lifecycle_hook is already implemented in API:

`POST /autoscaling-api/v1/{project_id}/scaling_lifecycle_hook/{scaling_group_id}`

 **Parameter description**
Parameter | Mandatory | Type | Description
-- | -- | -- | --
project_id | Yes | String | Specifies the project ID.
scaling_group_id | Yes | String | Specifies the AS group ID.

**Request parameters**
Parameter | Mandatory | Type | Description
-- | -- | -- | --
lifecycle_hook_name | Yes | String | Specifies the lifecycle hook name. The name contains only letters, digits, underscores (_), and hyphens (-), and cannot exceed 32 characters.
lifecycle_hook_type | Yes | String | Specifies the lifecycle hook type. Options:INSTANCE_TERMINATING: The hook suspends the instance when the instance is terminated.INSTANCE_LAUNCHING: The hook suspends the instance when the instance is started.
default_result | No | String | Specifies the default lifecycle hook callback operation. By default, this operation is performed when the timeout duration expires.ABANDONCONTINUENOTE:If an instance is starting, CONTINUE indicates that your customized operations are successful and the instance can be used. ABANDON indicates that your customized operations failed, and the instance will be terminated. In such a case, the scaling action fails, and you must create a new instance.If an instance is stopping, both ABANDON and CONTINUE allow instance termination. The difference between the two states is as follows: ABANDON stops other lifecycle hooks, but CONTINUE allows the completion of other lifecycle hooks.The default value of this parameter is ABANDON.
default_timeout | No | Integer | Specifies the lifecycle hook timeout duration, which ranges from 300 to 86400 in the unit of second. The default value is 3600.By default, this parameter specifies the instance waiting duration. You can prolong the timeout duration or perform the CONTINUE or ABANDON operation before the timeout duration expires.
notification_topic_urn | Yes | String | Specifies a unique topic in SMN.This parameter specifies a notification object for a lifecycle hook. When an instance is suspended by the lifecycle hook, the SMN service sends a notification to the object. This notification contains the basic instance information, your customized notification content, and the token for controlling lifecycle operations.
notification_metadata | No | String | Specifies a customized notification, which contains no more than 256 characters in length. The message cannot contain the following characters: <>&'()After a notification object is configured, the SMN service sends your customized notification to the object.

**API Example:**
```
POST https://{Endpoint}/autoscaling-api/v1/{project_id}/scaling_lifecycle_hook/e5d27f5c-dd76-4a61-b4bc-a67c5686719a

{
    "lifecycle_hook_name": "test-hook1",
    "default_result": "ABANDON",
    "default_timeout": 3600,
    "notification_topic_urn": "urn:smn:regionId:b53e5554fad0494d96206fb84296510b:gsh",
    "lifecycle_hook_type": "INSTANCE_LAUNCHING"
}
```

Currently there is no way to create or link a lifecycle hook to an AS Group using terraform.

Thank you in advance,
Alex

**Comment by qukuijin1989** [comment]
hi @alpersid 
we will delivery this feature at the middle of june
cc to @shichangkuo
