### ISSUE TITLE
[WAFaaS] Ressource is missing

### ISSUE THREAD

**Issue by antonin-a** [FlexibleEngineCloud/terraform-provider-flexibleengine#533]
Hi there,

WAFaaS is currently available on Flexible Engine cloud (https://docs.prod-cloud-ocb.orange-business.com/api/waf/waf_02_0102.html)  but the Terraform resource is not available here. Is it possible to add it ? 

Regards

**Comment by qukuijin1989** [comment]
@antonin-a 
i will check it, when can we add Waf
