### ISSUE TITLE
S3 Api - Acceptance tests - connection reset by peer

### ISSUE THREAD

**Issue by Benjile** [FlexibleEngineCloud/terraform-provider-flexibleengine#537]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
terraform 13.6 and terraform 14.7

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_flexibleengine_s3_bucket

It probably occurs with any S3 object

### Terraform Configuration Files
We are running provider acceptance tests

### Debug Output
https://gist.github.com/Benjile/cb60fc4f6c5f5ab05f6e947a3dc2e320

### Expected Behavior
Acceptance tests should pass

### Actual Behavior
Acceptance tests fails

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `make testacc TEST='./flexibleengine' TESTARGS='-run TestAccS3Bucket_basic'`

### Important Factoids
We are having theses issues since 12 may in the morning. We can observe on several of our configurations some connection reset. All of our configurations using s3 api fully fail with a reset by peer.
You can easily reproduce it in acceptances tests
We think a change has been done in the api breaking the terraform provider

**Comment by ShiChangkuo** [comment]
Hi @Benjile 

Thanks for raising this. Did you run the acceptance testing on the latest master brance?
I also encounter this issue using previous versions with AK/SK auth.
@antonin-a @qukuijin please have a look at this issue. Has the IAM service do any breaking changes?

**Comment by Benjile** [comment]
I tested it on 1.12.1 and 1.19.1 and master every time with AK/SK auth. 
I thought the S3 api forced us to use AK/SK a few month ago. I've just retried with username/password and it seems the s3 api works with this auth method. Maybe this requirement changed on the api side or my memory plays me some tricks, dunno...
Whatever, it seems the acceptance test does not end in tcp connection reset with username/password auth method

**Comment by antonin-a** [comment]
Hello @Benjile I do confirm that it was working perfectly using AK/SK but I'm now facing the exact same issue. We are investigating

**Comment by Benjile** [comment]
thanx @antonin-a 
An issue has been raised with FE support too

**Comment by Benjile** [comment]
Acceptance tests works now. The issue has been solved by FE team.
