### ISSUE TITLE
[RDS] SG not found with provider 1.21.0

### ISSUE THREAD

**Issue by sbernier-corp** [FlexibleEngineCloud/terraform-provider-flexibleengine#548]
Hi there,

When moving from Provider from 1.20.0 to 1.21.0 we are no more able to deploy RDS servers due to following error:

Error: Error creating FlexibleEngine RDS instance: Resource not found: [POST https://rds.eu-west-0.prod-cloud-ocb.orange-business.com/v3/80ba4a1aac8745eda535af39aa9ee2d1/instances], error message: {"error_msg":"Security group ID does not exist.","error_code":"DBS.200502"}

When reverting to provider 1.20.0 same code works fine.

Then when moving back to provider 1.21.0, if we redo a Terraform apply the previously created RDS is ignored and Terraform wants to create a new RDS server.

### Terraform Version
Terraform v0.13.7

### Affected Resource(s)
- flexibleengine_rds_instance_v3

### Expected Behavior
RDS server to be created from all version of provider and manageable from any version.

### Actual Behavior
Provider 1.21 not able to create RDS with Security group.
Provide 1.21 ignores previously created RDS.

### Steps to Reproduce
Issue 1: Create a RDS with provider 1.21 with SG, you should get the following error :
Error: Error creating FlexibleEngine RDS instance: Resource not found: [POST https://rds.eu-west-0.prod-cloud-ocb.orange-business.com/v3/80ba4a1aac8745eda535af39aa9ee2d1/instances], error message: {"error_msg":"Security group ID does not exist.","error_code":"DBS.200502"}

Issue 2: 
1. Create a RDS with 1.20 provider
2. Try to update same stack with Provider 1.21
You should see that Previously created RDS is ignored and that a new RDS server needs to be created

**Comment by ShiChangkuo** [comment]
@sbernier-corp Do you use the same `security_group_id` between v1.20 and v1.21?
if yes, can you provide the configuration script or logging file?

**Comment by sbernier-corp** [comment]
yes I used the same security_group_id.
I was using the same stack for the test with 1.21 and 1.20.

**Comment by ShiChangkuo** [comment]
I tested well in my local machine with an existing security_group_id, and also encountered the same error with an un-existing security_group_id.

if the security group was created dynamically, please check it is not destroyed before using it.

**Comment by sbernier-corp** [comment]
Hi ShiChangkuo,

Thank you for your answer.
Unfortunately, it does not work on my side.
Same code works with flexibleengine version 1.20 but fails with 1.21.
With error: 
Error: Error creating FlexibleEngine RDS instance: Resource not found: [POST https://rds.eu-west-0.prod-cloud-ocb.orange-business.com/v3/80ba4a1aac8745eda535af39aa9ee2d1/instances], error message: {"error_msg":"Security group ID does not exist.","error_code":"DBS.200502"}

Security already exists before the stack is ran, and the Id is fetch with a data so no issue on that side.

Can you check that you were with the 1.21 provider when you tested ?

Can you also check my second issue ?
When creating RDS with 1.20 and try to update with 1.21 ?
It should try to create a new database ...

Thanks,

**Comment by ShiChangkuo** [comment]
It also works well when I created a RDS instance with 1.20, and then updated the provider to 1.21.

can you supply the your tf script and the [log file](https://docs.prod-cloud-ocb.orange-business.com/usermanual/terraform/terraform_0004.html)?

**Comment by sbernier-corp** [comment]
Please find the log archive [Logs_16_06_21.zip](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/6664095/Logs_16_06_21.zip)
There is 3 files
  + rds-creation-provider-1.21.out: trying to create rds with security group issue when using provider 1.21
  + rds-creation-provider-1.20.out: Creating rds working with provider 1.20
  + rds-update-provider-from-1.20-to-1.21.out: issue when trying to update RDS with 1.21 provider when RDS was created with provider 1.20

**Comment by sbernier-corp** [comment]
Please find the correspnding TF code 
[rds.tar.gz](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/6664321/rds.tar.gz)

**Comment by ShiChangkuo** [comment]
@sbernier-corp Did the rds instance locate in a sub-project of eu-west-0?

**Comment by sbernier-corp** [comment]
Yes the rds is located in sub project under eu-west-0 for my test environment and also for the customer environment.

**Comment by ShiChangkuo** [comment]
ok, I'll test it in a sub project, and try to fix it as soon as I can.
