### ISSUE TITLE
provider produced an unexpected new value

### ISSUE THREAD

**Issue by tundragon** [FlexibleEngineCloud/terraform-provider-flexibleengine#569]
Hi there,

### Terraform Version
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.21.0

### Affected Resource(s)
- ecs create

### Terraform Configuration Files
terraform {
  required_providers {
    flexibleengine = {
      source = "FlexibleEngineCloud/flexibleengine"
      version = "1.21.0"
    }
  }
}

provider "flexibleengine" {
  access_key  = "abcd"
  secret_key  = "1234"
  domain_name = "OCB..."
  auth_url    = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
  region      = "eu-west-0"
}

resource "flexibleengine_compute_instance_v2" "basic" {
  name            = "ecs-name"
  image_id        = "a785085a-f217-4a4b-abc8-ba143691ba7e"
  flavor_name     = "s3.small.1"
  key_pair        = "oro-key"
  security_groups = ["default"]

network {
    uuid = "39fa4c43-8f40-4bf8-9d5e-1ac37993c5eb"
  }
}

### Debug Output
https://gist.github.com/tundragon/137b98afb5ba144028d83b2028747491#file-terraform-fe-ecs_create

### Expected Behavior
Terraform should know that the ECS is created and it should not create another ECS if i run `terraform apply` again.

### Actual Behavior
Terraform sends the POST command to create the ECS. 
The ECS gets created in Flexible Engine.
Terraform throws an error and, from Terraform's point of view the ECS does not get created.
If i run `terraform apply` again, the ECS gets created again, with the same parameters.

### Steps to Reproduce
`terraform apply`

**Comment by tundragon** [comment]
I have upgraded to flexible engine 1.22 but i am still getting this error

https://gist.github.com/tundragon/b71fc5bb71cbb556be08e62a4e4d6d49

**Comment by ShiChangkuo** [comment]
Hi, @tundragon I can not reproduce the issue with same terraform version.

can you get the ecs instance in console?

**Comment by tundragon** [comment]
Hello @ShiChangkuo .

Yes, the ECS gets created in Flexible Engine console.

The problem is that Terraform does not see it as created, thus it cannot get destroyed.
If i run the terraform script again, the ECS gets created again, as a different ECS with the same properties.

I have tried from another PC and I get the same error.

**Comment by ShiChangkuo** [comment]
can you provide the debug log through [How Do I View Terraform Logs?](https://docs.prod-cloud-ocb.orange-business.com/usermanual/terraform/terraform_0004.html)

**Comment by tundragon** [comment]
[trace.log](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/6776312/trace.log)

Hello @ShiChangkuo 
Attached.

**Comment by ShiChangkuo** [comment]
@tundragon please try to add *tenant_name = "eu-west-0"* in the provider block.

**Comment by tundragon** [comment]
Hello,
It is working.

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.


I do not understand why, as it is optional.
https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs

**Comment by ShiChangkuo** [comment]
Now, at least one of  `tenant_name` and `tenant_id` must be specified.
I will make `tenant_name` default to **region** in the feature, then it will be an optional field.
