### ISSUE TITLE
Alarm rule always created in default project

### ISSUE THREAD

**Issue by smasset-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#570]
We're testing alarm rule creation on RDS DB disk usage which should send email alert through SMN topic.

Our terraform configuration file contains RDS DB, topic, topic subscription, and alarm rule resources which should be created in a specific sub project.

All resources are correctly created (terraform apply succeeds) but the alarm rule is created in the default project and not in the same project as the other resources. 

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_ces_alarmrulee

### Terraform Configuration Files
See attached [rds.tf.txt](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/6749443/rds.tf.txt)

### Expected Behavior
The alarm rule should be created in the same project as the other resources

### Actual Behavior
The alarm rule is created in default project

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with attached [rds.tf.txt](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/6749443/rds.tf.txt)

**Comment by smasset-orange** [comment]
cc to @sbernier-corp

Hi @ShiChangkuo, any ETA for v1.23.0 release ?

**Comment by ShiChangkuo** [comment]
@smasset-orange could you upgrade the provider to the latest  version, and test again?
I think the issue has been solved after v1.22.0+

**Comment by sbernier-corp** [comment]
Hi ShiChankuo,
As Sebastien is on vacation, I have done the test and it works fine with 1.22 version of the provider.

**Comment by ShiChangkuo** [comment]
Sounds great!

@sbernier-corp @smasset-orange 
I'm going to close this issue, if you have found a problem that seems similar to this, please feel free to open a new issue.
