### ISSUE TITLE
[IMS] Cannot set BIOS mode

### ISSUE THREAD

**Issue by francois-travais** [FlexibleEngineCloud/terraform-provider-flexibleengine#572]
### Terraform Version
```bash
$ terraform version
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.21.0
+ provider registry.terraform.io/poseidon/ct v0.8.0
```
### Affected Resource(s)

- flexibleengine_images_image_v2

### Expected Behavior
Having an argument available to set the BIOS mode. By default it's set to legacy BIOS, however I would like to use UEFI.

### Actual Behavior
No argument provided to do so.

### References

The console documentation describing the BIOS mode option: https://docs.prod-cloud-ocb.orange-business.com/usermanual/ims/en-us_topic_0030713193.html

**Comment by ShiChangkuo** [comment]
Hi @francois-travais 
seems the corresponding APIs are [Importing an Image File Quickly](https://docs.prod-cloud-ocb.orange-business.com/api/ims/en-us_topic_0133188204.html) or [Creating Image Metadata (Native OpenStack API)](https://docs.prod-cloud-ocb.orange-business.com/api/ims/en-us_topic_0031615565.html), but neither of them has `boot mode` field.

pleae open a ticket to IMS service in cloud side firstly.

cc to @qukuijin @antonin-a

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
