### ISSUE TITLE
flexibleengine_fw_rule_v2 removal issue

### ISSUE THREAD

**Issue by marius-oro** [FlexibleEngineCloud/terraform-provider-flexibleengine#574]
Hi there,

I am trying to use terraform to manage Flexible Engine Network ACLs. All good, I can create ALCs and rules (either by using flexibleengine_network_<resource> or flexibleengine_fw_<resource>). The problem comes when I try to destroy an existing rule from the network ACL. Using flexibleengine_fw_policy_v2 and flexibleengine_fw_rule_v2 resources, whenever I remove the code for the rule (to trigger its destruction) and update the policy (removing the mentioned rule) I get an error with the rule being used

### Terraform Version
1.0.1

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_fw_policy_v2

### Terraform Configuration Files
```hcl
/* Initial code */

resource "flexibleengine_fw_rule_v2" "rule_1" {
  name             = "my-rule-1"
  description      = "drop TELNET traffic"
  action           = "deny"
  protocol         = "tcp"
  destination_port = "23"
  enabled          = "true"
}

resource "flexibleengine_fw_rule_v2" "rule_2" {
  name             = "my-rule-2"
  description      = "drop NTP traffic"
  action           = "deny"
  protocol         = "udp"
  destination_port = "123"
  enabled          = "false"
}

resource "flexibleengine_fw_policy_v2" "policy_1" {
  name = "my-policy"

  rules = ["${flexibleengine_fw_rule_v2.rule_1.id}",
    "${flexibleengine_fw_rule_v2.rule_2.id}",
  ]
}

resource "flexibleengine_fw_firewall_group_v2" "firewall_group_1" {
  name              = "my-firewall-group"
  ingress_policy_id = flexibleengine_fw_policy_v2.policy_1.id
}

```
The above code successfully creates the following objects:
- two flexibleengine_fw_rule_v2 named rule_1 and rule_2
- one flexibleengine_fw_policy_v2 named policy_1 with the two rules attached
- one flexibleengine_fw_firewall_group_v2 named firewall_group_1 with the above policy attached

Updating the code to following (in order to remove second rule and update the policy)
```hcl
resource "flexibleengine_fw_rule_v2" "rule_1" {
  name             = "my-rule-1"
  description      = "drop TELNET traffic"
  action           = "deny"
  protocol         = "tcp"
  destination_port = "23"
  enabled          = "true"
}

resource "flexibleengine_fw_policy_v2" "policy_1" {
  name = "my-policy"

  rules = ["${flexibleengine_fw_rule_v2.rule_1.id}"]
}

resource "flexibleengine_fw_firewall_group_v2" "firewall_group_1" {
  name              = "my-firewall-group"
  ingress_policy_id = flexibleengine_fw_policy_v2.policy_1.id
}
```
generates the proper plan (destroy the rule_2 and update the policy):
```
Terraform will perform the following actions:

  # flexibleengine_fw_policy_v2.policy_1 will be updated in-place
  ~ resource "flexibleengine_fw_policy_v2" "policy_1" {
        id        = "not-actual-id"
        name      = "my-policy"
      ~ rules     = [
            "not-actual-id",
          - "not-actual-id",
        ]
        # (4 unchanged attributes hidden)
    }

  # flexibleengine_fw_rule_v2.rule_2 will be destroyed
  - resource "flexibleengine_fw_rule_v2" "rule_2" {
      - action           = "deny" -> null
      - description      = "drop NTP traffic" -> null
      - destination_port = "123" -> null
      - enabled          = false -> null
      - id               = "not-actual-id" -> null
      - ip_version       = 4 -> null
      - name             = "my-rule-2" -> null
      - protocol         = "udp" -> null
      - region           = "eu-west-0" -> null
    }

Plan: 0 to add, 1 to change, 1 to destroy.
```
### Expected Behavior
Resources updated, having one network acl with just rule_1

### Actual Behavior
Terraform apply fails with the following:

```
flexibleengine_fw_rule_v2.rule_2: Destroying... [id=not-actual-id]
╷
│ Error: Expected HTTP response code [202 204] when accessing [DELETE https://vpc.eu-west-0.prod-cloud-ocb.orange-business.com/v2.0/fwaas/firewall_rules/not-actual-id], but got 409 instead
│ {"NeutronError": {"message": "Firewall Rule not-actual-id is being used.", "type": "FirewallRuleInUse", "detail": ""}}
│
```

### Steps to Reproduce

1. Create a firewall policy with multiple rules plan
2. Apply the code
2. Remove one rule from the plan and update the policy by removing the deleted rule from the ```rules ``` argument
3. Apply the code

**Comment by ShiChangkuo** [comment]
@marius-oro Thanks for raising this.

I also encountered the issue.
When we execute apply command at the last step, terraform should update the policy to unbind rule_2 **firstly**, then try ro delete the rule.
Unfortunately the order is reversed.

I think the root reason is caused by terraform.
You can apply the code after updating the policy by removing rule_2, and then apply it again after removing rule_2 in the code.

**Comment by marius-oro** [comment]
> @marius-oro Thanks for raising this.
> 
> I also encountered the issue.
> When we execute apply command at the last step, terraform should update the policy to unbind rule_2 **firstly**, then try ro delete the rule.
> Unfortunately the order is reversed.
> 
> I think the root reason is caused by terraform.
> You can apply the code after updating the policy by removing rule_2, and then apply it again after removing rule_2 in the code.

@ShiChangkuo thanks for taking a look.
Unfortunately, doing the removal in two steps is not applicable because we intend to build and maintain the rules automatically. For example, we have a set of N instances (count = N) we want to add to the ACL filtering, thus we will build N rules for the ACL. We are doing this by having a for clause which builds the rules based on the count index of the instances. 
The N number is dynamic, meaning it can become N+M or N-M. Whenever it becomes N-M, this terraform plan should automatically remove the extra M rules (so it's just one step, we could not do it in 2 steps).

**Comment by ShiChangkuo** [comment]
same issue with hashicorp/terraform#20196

Setting the resource's lifecycle to create before destroy will solve it, you can have a try.

```
resource "flexibleengine_fw_rule_v2" "rule_2" {
  ...
  lifecycle  {
    create_before_destroy=true
  }
}
```

**Comment by marius-oro** [comment]
> same issue with [hashicorp/terraform#20196](https://github.com/hashicorp/terraform/issues/20196)
> 
> Setting the resource's lifecycle to create before destroy will solve it, you can have a try.
> 
> ```
> resource "flexibleengine_fw_rule_v2" "rule_2" {
>   ...
>   lifecycle  {
>     create_before_destroy=true
>   }
> }
> ```

You're absolutely on point! I can confirm this is working. Thank you very much for you quick reaction.
