### ISSUE TITLE
Migration to terraform-plugin-sdk/v2

### ISSUE THREAD

**Issue by xescugc** [FlexibleEngineCloud/terraform-provider-flexibleengine#586]
I left the template headers but it does not fit with them.

Basically Terraform released a while back the v2 of the sdk https://github.com/hashicorp/terraform-plugin-sdk and I was wondering if this Provider was intending to migrate to it.

I'll work on a PR for it as I need it for a project I'm working on. I'll open the PR to this repo too just in case it's wanted. Sometimes this changes are big and require some more internal testing that's why I'm asking beforehand too hehe.

**Comment by ShiChangkuo** [comment]
@xescugc What‘s the benefit of using the v2 sdk for your project?

**Comment by xescugc** [comment]
"Benefit" none actually.

At the company I work for we have several OSS projects related to tools around Terraform (https://github.com/cycloidio/terracognita, https://github.com/cycloidio/inframap and https://github.com/cycloidio/terracost) and also some internal products that are build on top of those tools: https://www.cycloid.io/stackcraft and https://www.cycloid.io/infraview.

For that I use common interfaces between the Providers but with the update from `v1` to `v2` all those interfaces are broken as they do not match types this affects several internal ongoing features right now as we use those tools internally. So I'm updating the Providers that do not use `v2` to use it.

**Comment by ShiChangkuo** [comment]
@xescugc I get it. As the SDK v2 has breaking changes, we should test it carefully. Let's implement it as the following timeline:

1. merge huaweicloud/terraform-provider-huaweicloud#1309 into **sdkv2** branch;
2. release a new version for FlexibleEngineCloud before 7.28;
3. import huaweicloud/terraform-provider-huaweicloud@sdkv2 package;
4. merge #587 
...

**Comment by xescugc** [comment]
Yes I know :).

For me right now I needed to at least have the code compiling with v2 to unblock my project, so I had to have the PRs and I opened them to see if they are useful/wanted for the project (FlexibleEngine and by extension HuaweiCloud). I konw that the actual release project will take a while as the changes are quite important and need to be tested carefully, I'm totally aware of that.
