### ISSUE TITLE
ZVHD disk format not supported

### ISSUE THREAD

**Issue by abhaysrivastava-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#601]
Hi there,

I am using zvhd disk format for my windows OS from which image need to create  but zvhd format not supported here.

What to do now. Please suggest.

**Comment by DafuSHI** [comment]
Hello @abhaysrivastava-orange 

It seems to be an issue for IMS service. Did you create a ticket on Flexible Engine? Here we handle issue related to FE Terraform

**Comment by abhaysrivastava-orange** [comment]
Ok I will contact Flexible Engine team.

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have any questions, please reopen it. Thanks.
