### ISSUE TITLE
Environment variables for Terraform with GitHub Actions

### ISSUE THREAD

**Issue by thomaskrampe** [FlexibleEngineCloud/terraform-provider-flexibleengine#610]
Try the Environment variables mentioned in the README as follows:
export OS_ACCESS_KEY=xxx
export OS_SECRET_KEY=xxx
export OS_REGION_NAME=xxx

But it seems that they don't work. Get this error from terraform plan:

Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/flexibleenginecloud/flexibleengine" requires explicit configuration. Add a provider block to the root
│ module and configure the provider's required arguments as described in the provider documentation.
│ 
╵
╷
│ Error: "password": one of `user_name, user_id` must be specified
│ 
│   with provider["registry.terraform.io/flexibleenginecloud/flexibleengine"],
│   on <input-prompt> line 1:

Does "explicit configuration" mean that I have to put my credentials (AS/SK) in cleartext into my .tf files on GitHub?

Thomas

**Comment by ShiChangkuo** [comment]
@thomaskrampe can it work on your local execution machine?

**Comment by thomaskrampe** [comment]
Had both in my env vars **OS_ACCESS...** and **OS_USER...** which seems to stop the whole process! You have to configure only one type ;-) 

And when using authentication with username / password the user variable is **OS_USERNAME** not **OS_USER_NAME**. Remove everything and use **OS_ACCESS_KEY** and **OS_SECRET_KEY** and everything works fine with GitHub Actions. Thanks.

**Comment by ShiChangkuo** [comment]
it seems that **OS_USER_NAME** is more suitable. I will support both OS_USERNAME and OS_USER_NAME to keep compatible, and recommend to use OS_USER_NAME in docs.

**Comment by thomaskrampe** [comment]
Only **OS_USERNAME** works, **OS_USER_NAME** currently not. I have just test it.Maybe it's a feature for the next release to make sure that it works both.
