### ISSUE TITLE
[Feature Request] Data Ingestion Service

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#620]
Hello, 

We have a service called Data Ingestion Service on Flexible Engine, but we don't have any Terraform resource associated to this service. It's possible to add this service on the Terraform provider resources?

Thanks, 

Regards,

Valentin LANDEMAINE (OCB/PS)

**Comment by gllb** [comment]
Hello,

I believe golangsdk does not support the DIS, and it might be a prerequisite for this feature.
Here the issue to support DIS in the sdk https://github.com/chnsz/golangsdk/issues/27

**Comment by ShiChangkuo** [comment]
@gllb any updates?
Can we not set the `stream_type` field if the API issue still exists?

**Comment by gllb** [comment]
Yes we can, here is a PR : https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/pull/656 
I guess it would be nice to have the right API result and documentation but we could still release this.

**Comment by gllb** [comment]
data_type and data_schema are also missing, so if a user try to set one of those missing value each plan will try to update the existing stream. IMO this is a real pain, specially for data_type and data_schema.
