### ISSUE TITLE
 [Feature Request] IAM : Project management

### ISSUE THREAD

**Issue by vlandemaine-orange** [FlexibleEngineCloud/terraform-provider-flexibleengine#621]
Hello, 

In the Flexible Engine console, on the IAM part, we can create/update/delete project through the interface. 

It is posssible to implement a specific resource in the Terraform provider to manage the projects?

Thanks.

Regards, 

Valentin LANDEMAINE (OCB/PS)

**Comment by antonin-a** [comment]
Hello @vlandemaine-orange , create/update is ok but deletion is currently not supported (considered as too risky). 
I agree that it would be nice to add IAM project management.

**Comment by ShiChangkuo** [comment]
@antonin-a what will the provider do when the project can not be deleted? ignore this step or report an error?

**Comment by antonin-a** [comment]
Hello @ShiChangkuo from API side it will return an error. 
Ex using Openstack CLI:
`cloud@CLI:~$ openstack project delete f137be38e2014ad296798ba45635f21a
Failed to delete project with name or ID 'f137be38e2014ad296798ba45635f21a': Policy doesn't allow iam:projects:deleteProject to be performed. (HTTP 403)
1 of 1 projects failed to delete.`

**Comment by gllb** [comment]
Hello I implemented the feature here : https://github.com/gllb/terraform-provider-flexibleengine/commit/963591b8c51ed94d7e92471974579b5070153d83 
For now the deletion func try to delete but it can be change to report an error or ignore it.
@ShiChangkuo what's is the contribution process ? Create PR's from a feature branch or something else ?

**Comment by ShiChangkuo** [comment]
@gllb Fantastic! You can create a PR and I will help you to review it.
