### ISSUE TITLE
flexibleengine_cce_addon_v3: documentation

### ISSUE THREAD

**Issue by q-b** [FlexibleEngineCloud/terraform-provider-flexibleengine#651]
Hi,

[Link to flexibleengine_cce_addon_v3 documentation](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/cce_addon_v3)

First [this example](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/cce_addon_v3#use-basic_json-custom_json-and-flavor_json) is wrong, fields named *something*`_json` do not work. They should be named `basic`, `custom` and `flavor` as stated futher down the page.

Next, for each of those arguments, the same typo is repeated:
> in json string **fomart**

should be **format**

**Comment by ShiChangkuo** [comment]
thanks for pointing this. I will fix it soon.
