### ISSUE TITLE
[Feature Request] OBS Cross-Region Replication

### ISSUE THREAD

**Issue by alexdotsh** [FlexibleEngineCloud/terraform-provider-flexibleengine#658]
Hi,

Currently in the Terraform code there is no ability to create OBS Cross-Region Replication in a new or existing bucket. Is this feature absent from the Terraform code and is it possible to add this feature in the Terraform?

There is already some documentation to enable cross-region replication https://docs.prod-cloud-ocb.orange-business.com/api/obs/en-us_topic_0175597491.html

It would be nice to add this feature in the Terraform code thanks

**Comment by ShiChangkuo** [comment]
same as #296

The [huaweicloud/huaweicloud-sdk-go-obs](https://github.com/huaweicloud/huaweicloud-sdk-go-obs) does not support Cross-Region replication. I wil try to add it first.

**Comment by alexdotsh** [comment]
@ShiChangkuo thanks for looking into this 👍🏽
