### ISSUE TITLE
Creating an MRS cluster

### ISSUE THREAD

**Issue by wisssaam** [FlexibleEngineCloud/terraform-provider-flexibleengine#659]
Hi there,

I've just started playing with Terraform provider for Flexible Engine (v1.25.1).

I have issues with creating an MRS cluster. Here's my configuration:

resource "flexibleengine_mrs_cluster_v1" "cluster" {
  region            = eu-west-0
  available_zone_id = eu-west-0a
  cluster_name      = var.name
  cluster_type      = 0
  cluster_version   = MRS 3.1.0-LTS.1

  master_node_num  = var.mrs_master_count
  core_node_num    = var.mrs_node_count
  master_node_size = var.mrs_master_type
  core_node_size   = var.mrs_node_type
  volume_type      = "SATA"
  volume_size      = 600
  vpc_id           = flexibleengine_vpc_v1.vpc.id
  subnet_id        = flexibleengine_vpc_subnet_v1.mrs.id

  safe_mode             = 0
  cluster_admin_secret  = var.mrs_manager_password
  node_public_cert_name = flexibleengine_compute_keypair_v2.keypair.id

  component_list {
    component_name = "Hadoop"
  }
  component_list {
    component_name = "Spark2x"
  }
  component_list {
    component_name = "Hive"
  }
  component_list {
    component_name = "Ranger"
  }
  component_list {
    component_name = "ZooKeeper"
  }
}

And variables:
mrs_master_type  = "c6.4xlarge.4.linux.mrs"
mrs_master_count = 2
mrs_node_type    = "c6.4xlarge.4.linux.mrs"
mrs_node_count   = 3

The apply results with error:
**Error waiting for cluster (2d582baa-afec-4fb1-a355-271f29ff9cae) to become ready: unexpected state 'failed', wanted target 'running'. last error: %!s(<nil>).**
Terraform runs for a few minutes and stops with this error

### Terraform Version
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.25.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_mrs_cluster_v1

**Comment by wisssaam** [comment]
We have this error only with MRS version 3

**Comment by ShiChangkuo** [comment]
@wisssaam can you provide the debug log? we can get more details about the reason for the issue.

**Comment by wisssaam** [comment]
Hello @ShiChangkuo, 
Attached:  [terraform.log](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/7685499/terraform.log)

**Comment by wisssaam** [comment]
And console screen:
[apply.txt](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/7685529/apply.txt)

**Comment by ShiChangkuo** [comment]
@wisssaam we should upgrade the API version to support MRS 3.1.0

**Comment by wisssaam** [comment]
Hello @ShiChangkuo, do you have any information about the update date? When do you plan to push the upgraded API version?

**Comment by ShiChangkuo** [comment]
now you can upgrade the provider version to 1.26.0 and try to ues [flexibleengine_mrs_cluster_v2](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/mrs_cluster_v2)
