### ISSUE TITLE
[flexibleengine_dns_zone_v2] Unable to create in na-east-0

### ISSUE THREAD

**Issue by grzegorzswistak** [FlexibleEngineCloud/terraform-provider-flexibleengine#664]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.25.1

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_dns_zone_v2

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.13"
  required_providers {
    flexibleengine = {
      source  = "FlexibleEngineCloud/flexibleengine"
      version = ">= 1.20.0"
    }
  }
}

# Configure the FlexibleEngine Provider with AK/SK
provider "flexibleengine" {
  access_key  = var.access_key
  secret_key  = var.secret_key
  domain_name = var.domain_name
  region      = "na-east-0"
  auth_url = "https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3"
}

resource "flexibleengine_dns_zone_v2" "private_dns_names" {
  name        = "${var.environment_name}."
  description = "Private zone form ${var.environment_name} enviroment"
  ttl         = 3000
  zone_type   = "private"

  router {
    router_id = data.flexibleengine_vpc_subnet_v1.subnet_1.vpc_id
  }
}
```

### Expected Behavior
I should be able to create flexibleengine_dns_zone_v2 in all regions on fe.

### Actual Behavior
I'm not able to create flexibleengine_dns_zone_v2 in na-east-0 region.

```
│ Error: Error creating FlexibleEngine DNS client: No suitable endpoint could be found in the service catalog.
│ 
│   with module.ccs.flexibleengine_dns_zone_v2.private_dns_names,
│   on ../../modules/ccs/main.tf line 29, in resource "flexibleengine_dns_zone_v2" "private_dns_names":
│   29: resource "flexibleengine_dns_zone_v2" "private_dns_names" {
│ 
╵
```

**Comment by ShiChangkuo** [comment]
@grzegorzswistak Thanks for raising this, I will fix it asap.
