### ISSUE TITLE
[DWS] Creating DWS Cluster

### ISSUE THREAD

**Issue by wisssaam** [FlexibleEngineCloud/terraform-provider-flexibleengine#674]
Hi there,

I have issues with the creating of DWS cluster (Terraform provider: Flexible Engine v1.26). 

Here's my configuration file  [main.txt](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/7756656/main.txt):

resource "flexibleengine_dws_cluster_v1" "cluster" {
  name                              = "dws_cluster_terraform"
  node_type                      = "dws2.m6.4xlarge.8"
  number_of_node            = 3
  user_name                      = "cluster_admin"
  user_pwd                        = "Cloud123@!"
  vpc_id                             = flexibleengine_vpc_v1.vpc.id

  subnet_id                       = flexibleengine_networking_network_v2.net.id
  security_group_id           = flexibleengine_networking_secgroup_v2.secgroup.id
  availability_zone = var.availability_zone
}

The apply results with error  LOG FILE [terraform-log.txt](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/files/7756657/terraform-log.txt):
_Error: Error creating DWS-Cluster: Internal Server Error: [POST https://dws.eu-west-0.prod-cloud-ocb.orange-business.com/v1.0/fa7426a17fe246698cf9a475f4254099/clusters], error message: {"errCode":"DWS.0005","externalMessage":"Server failure."}_

**Comment by ShiChangkuo** [comment]
@wisssaam it's better to open a service ticket as the error comes from the cloud side.

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
