### ISSUE TITLE
[DIS] Creating a DIS Stream

### ISSUE THREAD

**Issue by wisssaam** [FlexibleEngineCloud/terraform-provider-flexibleengine#675]
Hi there,

I am trying to deploy DIS Stream to ingest specific data formats like CSV and JSON. The problem is that we can't configure the data_type and data_schema parameters.

These parameters seem to be available on the API Endpoint (https://docs.prod-cloud-ocb.orange-business.com/en-us/api/dis/dis_02_0016.html).

flexibleengine_dis_stream on TF version 1.26.0

Thanks,

**Comment by ShiChangkuo** [comment]
hello, we just keep the same behavior as the console.

**Comment by ShiChangkuo** [comment]
@wisssaam I will close it temporarily, If you have any questions, please reopen it. Thanks.
