### ISSUE TITLE
[Feature Request]  RDS - Support enable SSL and output RDS certificats

### ISSUE THREAD

**Issue by But4ler** [FlexibleEngineCloud/terraform-provider-flexibleengine#725]
Hi there,

It is possible via the Flexible Engine console to activate SSL on the RDS, and to download the certificate to deploy it on the servers.

![image](https://user-images.githubusercontent.com/15019378/159330145-298445f1-09cd-4c6f-b213-45b4848eeabb.png)

Would it be possible to add this to the RDS module please?
You also need the SSL certificate as an output of the module

Thank you!

**Comment by ShiChangkuo** [comment]
@But4ler we can support to enable SSL with terraform, but can not download the certificate. you can download it from
https://oss.eu-west-0.prod-cloud-ocb.orange-business.com/rds/ca-rds.zip

**Comment by But4ler** [comment]
it will be great, we don't check the certificate, 

Thank you!
