### ISSUE TITLE
Enhanced Load Balancer in front of 2 ECS

### ISSUE THREAD

**Issue by ahmed1mostafa** [FlexibleEngineCloud/terraform-provider-flexibleengine#726]
Hi there,

customer  create by terraform an enhanced Load Balancer in front of 2 ECS (with just the service nginx installed on it to make test) in FE tenant using this documentation : https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs

### Affected Resource(s)
-Health-check
the result is a pool of backend servers in "Disabled" state Nothing seems be able to correct their status, except destroy pool, monitor and members, and recreate all with the only correction setting default value for xxx_timeout arguments

**Comment by ahmed1mostafa** [comment]
Dears , 
anyone could help ?

**Comment by vlandemaine-orange** [comment]
Hello, 

Do you have tried to deploy it with the interface before using Terraform ? This issue is only related to Terraform ?

Regards

**Comment by ShiChangkuo** [comment]
@ahmed1mostafa I think the issue has been solved , can we close it?

**Comment by ShiChangkuo** [comment]
I will close it temporarily, If you have any questions, please reopen it. Thanks.
