### ISSUE TITLE
Following CTS upgrade, terraform is failing for plan/apply

### ISSUE THREAD

**Issue by agoulamhoussen** [FlexibleEngineCloud/terraform-provider-flexibleengine#727]
### Terraform Version
Terraform v1.0.11 (reproduced it with Terraorm 1.1.7 as well)

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_cts_tracker_v1

### Terraform Configuration Files
```hcl
resource "flexibleengine_obs_bucket" "cts_bucket" {
  bucket   = "cts-${terraform.workspace}"
  acl      = "private"
  multi_az = true

  lifecycle_rule {
    name    = "90days-delete"
    enabled = true

    expiration {
      days = 90
    }
  }
}

resource "flexibleengine_cts_tracker_v1" "cts_tracker" {
  bucket_name = flexibleengine_obs_bucket.cts_bucket.bucket
}
```

### Debug Output
https://gist.github.com/agoulamhoussen/715a88b365d1877a3baa7952f85cd250

### Expected Behavior
work as usual

### Actual Behavior
Whole plan/apply is failing; Partial plan/apply (using -target option)  excluding cts resource is working

### Steps to Reproduce

1. `terraform apply` or  `terraform plan` (probably need a state first, using `terraform import`)

### Important Factoids

* The issue arised when I tried to run a `terraform apply` on an existing state (with changes  not related to CTS tracker) 
* I tried to remove the existing state, and reimport it; the `terraform import` worked, but did not put in the state the bucket name; running afterwards `terraform apply` to add the missing bucket information ends up in a similar stacktrace
``` 
# relevant part of the imported state
{
      "mode": "managed",
      "type": "flexibleengine_cts_tracker_v1",
      "name": "cts_tracker",
      "provider": "provider[\"registry.terraform.io/flexibleenginecloud/flexibleengine\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "bucket_name": "", <------------- missing bucket name
            "file_prefix_name": "",
            "id": "system",
            "region": "eu-west-0",
            "status": "enabled",
            "timeouts": {
              "create": null,
              "delete": null
            },
            "tracker_name": "system"
          },
          "sensitive_attributes": [],
          "private": "<redacted>"
        }
      ]
    },
```

**Comment by agoulamhoussen** [comment]
It started to work at te end of thursday, probably some leftovers from the upgrade, but outside the maintenance window...

**Comment by ShiChangkuo** [comment]
@agoulamhoussen I found that the API response is different with [help center](https://docs.prod-cloud-ocb.orange-business.com/api/cts/en-us_topic_0169873588.html).
I also test it well today ...
