### ISSUE TITLE
[FGS] Can't create function in FGS

### ISSUE THREAD

**Issue by picklescloud** [FlexibleEngineCloud/terraform-provider-flexibleengine#736]
Hi there,

Can't create a function in Function Graph Service, it seems that FGS API is not accessible :
│ Error: Error creating FlexibleEngine function: Post "https://fgs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/482ea20d5304444599335a9d555fa70e/fgs/functions": dial tcp: lookup fgs.eu-west-0.prod-cloud-ocb.orange-business.com on 127.0.0.53:53: no such host

### Terraform Version
terraform -v
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.28.0

### Affected Resource(s)
Function Graph Service (FGS)

### Terraform Configuration Files
resource "flexibleengine_identity_agency_v3" "test" {
  name                   = "agency_1"
  description            = "test agency for fgs"
  delegated_service_name = "op_svc_cff"

  project_role {
    project = "eu-west-0"
    roles   = [
      "VPC Administrator",
      "SFS Administrator",
    ]
  }
}

resource "flexibleengine_fgs_function" "f_1" {
  name        = "func_1"
  app         = "default"
  agency      = "test"
  description = "fuction test"
  handler     = "test.handler"
  memory_size = 128
  timeout     = 3
  runtime     = "Python2.7"
  code_type   = "inline"
  func_code   = <<EOF
# -*- coding:utf-8 -*-
import json
def handler (event, context):
    return {
        "statusCode": 200,
        "isBase64Encoded": False,
        "body": json.dumps(event),
        "headers": {
            "Content-Type": "application/json"
        }
    }
EOF
}

### Debug Output
flexibleengine_identity_agency_v3.test: Creation complete after 1s [id=816f7cc1e3554e99a14fd89e70f241fe]
╷
│ Error: Error creating FlexibleEngine function: Post "https://fgs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/482ea20d5304444599335a9d555fa70e/fgs/functions": dial tcp: lookup fgs.eu-west-0.prod-cloud-ocb.orange-business.com on 127.0.0.53:53: no such host
│ 
│   with flexibleengine_fgs_function.f_1,
│   on fgs-function.tf line 15, in resource "flexibleengine_fgs_function" "f_1":
│   15: resource "flexibleengine_fgs_function" "f_1" {
│ 
╵

### Expected Behavior
Should create a function Function Graph Service

### Actual Behavior
Can't create function in Function Graph Service

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Regards,

Pierre

**Comment by ShiChangkuo** [comment]
according to [Creating a Function](https://docs.prod-cloud-ocb.orange-business.com/api/functiongraph/functiongraph_06_0108.html), the URI is correct.
have you tried to call the API directly with postman or curl command?

**Comment by picklescloud** [comment]
curl https://fgs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/482ea20d5304444599335a9d555fa70e/fgs/functions
curl: (6) Could not resolve host: fgs.eu-west-0.prod-cloud-ocb.orange-business.com

**Comment by ShiChangkuo** [comment]
It looks like a network issue, please check your networking configuration or open a service ticket in OCB.

```
$ curl https://fgs.eu-west-0.prod-cloud-ocb.orange-business.com/v2/482ea20d5304444599335a9d555fa70e/fgs/functions
{"error_msg":"Incorrect IAM authentication information: x-auth-token not found","error_code":"APIGW.0301","request_id":"5fb48b471fb1bab3cb9ce6c33255cf41"}
```

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
