### ISSUE TITLE
Unable to attach a security group to DCS Redis 5.0

### ISSUE THREAD

**Issue by gerardbonneto** [FlexibleEngineCloud/terraform-provider-flexibleengine#779]
Hi there,

### Terraform Version
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.31.0

### Affected Resource(s)
- dcs_instance

### Panic Output
 Error: Error updating FlexibleEngine Dcs Instance: Bad request with: [PUT https://dcs.eu-west-0.prod-cloud-ocb.orange-business.com/v1.0/aa5e4a9dd208442bb3f4b3d94b10c0cf/instances/8bbc33ce-05fe-4f22-a4e0-d00c860740a8], error message: {"error":{"code":"DCS.4872","message":"Do not support security group whitelist.","ext_message":null}}

**Comment by ShiChangkuo** [comment]
@gerardbonneto The security group can be configured only for instances that use Redis 3.0.
DCS for Redis 4.0 and 5.0 are based on VPC endpoints and do not support security groups.

**Comment by gerardbonneto** [comment]
Thanks for your answer.
IMO, the documentation should be updated with a comment saying that the argument "security_id" is optional and only supported for Redis 3.0.

**Comment by ShiChangkuo** [comment]
The parameter description is as follows:
https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/dcs_instance_v1#security_group_id
* `security_group_id` - (Optional) Specifies the id of the security group which the instance belongs to. This parameter is mandatory for Memcached and Redis 3.0 versions.
