### ISSUE TITLE
Failed to install autoscaller in a nodepool deployed in a new tenant

### ISSUE THREAD

**Issue by gerardbonneto** [FlexibleEngineCloud/terraform-provider-flexibleengine#780]
Hi there,
Terraform Version

Terraform v1.2.4
on linux_amd64

    provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.31.0

Affected Resource(s)

    cce_addon_v3

Panic Output

│ cluster-autoscaler-6869844d8-lvzgt:F0711 16:44:25.915777       1 hws_cloud_provider.go:154] Failed to create HWS Manager: Unexpected Response error, StatusCode: 401, Error Message: {"error_msg":"Incorrect IA │
│ M authentication information: get token error,status:400","error_code":"APIGW.0301","request_id":"415253e4c6ed63c9b7f4f5218e92aa62"}

**Comment by gerardbonneto** [comment]
From the default tenant, everything worked well
From a new create tenant: I could install the autocaller addon only from the console not from terraform.

**Comment by ShiChangkuo** [comment]
@gerardbonneto Is the panic output from terraform or other processes?
Also you can check if the new tenant has sufficient permissions.

**Comment by gerardbonneto** [comment]
The listed panic output is from terraform.
The tenant seems to have sufficient permissions:


**Functionalities | Families | Roles**

Billing | Customer space | No role
Contracts | Customer space | Account Manager
Orders | Customer space | Visitor
Services | Customer space | Manager
Subscriptions | Customer space | Manager
Support | Customer space | Visitor
Users | Customer space | Manager


**Functionalities | Families | Roles**

Flexible Engine console | Technical Console | admin


Furthermore, we have defined 2 agencies for the new tenant, namely cce_admin_trust and css_obs_agency.

**Comment by gerardbonneto** [comment]
Any update?

**Comment by ShiChangkuo** [comment]
@gerardbonneto actually, the provider does not have any files named hws_cloud_provider.go

**Comment by ShiChangkuo** [comment]
I'm going to close this issue because there are no updates for 20 days.
If you have found a problem that seems similar to this, please open a new issue and complete the issue template so we can capture all the details necessary to investigate further.
