### ISSUE TITLE
[CCE] [Feature request] Provide cluster certificates as a datasource

### ISSUE THREAD

**Issue by edouardhue** [FlexibleEngineCloud/terraform-provider-flexibleengine#796]
### Expected Behavior
It would be nice if there was a datasource that would retrieve the cluster certificates for the current user. It would make it possible to use these to connect to the cluster and use [the official kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) to manage resources without relying on a single Terraform state or an external storage for these credentials.

Attributes related to the certificate in the `flexibleengine_cce_cluster_v3` could then be deprecated, as they depend on the current user which makes the state change even if the cluster is unchanged (as stated in #741).

### Actual Behavior
Cluster certificates are available only in the `flexibleengine_cce_cluster_v3` resource.

### References
- [Obtaining Cluster Certificates](https://docs.prod-cloud-ocb.orange-business.com/api2/cce/cce_02_0248.html) via the API

**Comment by ShiChangkuo** [comment]
@edouardhue we will add a new data source `flexibleengine_cce_clusters` to get an array of CCE clusters
