### ISSUE TITLE
Issue with config_drive in flexible engine terraform provider

### ISSUE THREAD

**Issue by davidasaadmikhailtadros** [FlexibleEngineCloud/terraform-provider-flexibleengine#805]
I have a problem with the ECS deployed on FE with terraform, I can't get the "config-drive" to work to configure them at boot.
In case I attach the network directly to the ECS, the cloud-init works fine, however, if I go through a port (config 2 commented below), it's the "config-drive" that should work because we don't have access to the metadata server, but it's not taken into account (tested on a vm fortigate or a ubuntu cloud)

resource "flexibleengine_compute_instance_v2" "fortigate" {
  count = var.instance_count
  name = "fortigate-test-${count.index + 1}"
  image_name = "shared-fgt-${var.fgt_version}"
  flavor_name = "s3.medium.4"

 \#config 1 : network attachment
  network {
    uuid = var.subnet_id
    fixed_ip_v4 = "${var.internal_fixed_ip}"
  }
 \#config 2 : attach a port directly to the network
  \      #network {
   \     #port = flexibleengine_networking_port_v2.sdwan_access_port[count.index].id
   \     # }
  user_data = "${file("${path.module}/user_data.txt")}"
  config_drive = "true"
}
I followed the doc here: https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/compute_instance_v2#instance-with-user-data-cloud-init

Case 1 with the attachment on the network:

Does the config-drive work on FE? If so, is there any special configuration to set up?

**Comment by ShiChangkuo** [comment]
sorry, the API does not support `config-drive` any more.

https://docs.prod-cloud-ocb.orange-business.com/api/ecs/en-us_topic_0068473331.html

**Comment by ShiChangkuo** [comment]
@davidasaadmikhailtadros I will close it temporarily, If you have any questions, please reopen it. Thanks.
