### ISSUE TITLE
Cannot create Master/Standby DCS (Redis) using the Version Engine 5.0

### ISSUE THREAD

**Issue by achraf2405** [FlexibleEngineCloud/terraform-provider-flexibleengine#814]
Hello,
I cannot use terraform to create DCS of type Master/standby or Single-node when i select the engine version 5.0 (it works with version 3.0).

### Terraform Version
1.2.7
### Flexible Engine terraform provider version
1.32.0

### Affected Resource(s)
- DCS (Redis 5.0)

I
### Terraform Configuration Files
```hcl
resource "flexibleengine_dcs_instance_v1" "instance_1" {
  name              = "test_dcs_instance"
  engine            = "Redis"
  engine_version    = "5.0"
  password          = var.my_password
  product_id        = "dcs.master_standby-h"
  capacity          = 2
  vpc_id            = flexibleengine_vpc_v1.vpc_1.id
  network_id        = flexibleengine_vpc_subnet_v1.subnet_1.id
  available_zones   = ["eu-west-0a"]
  save_days         = 1
  backup_type       = "manual"
  begin_at          = "00:00-01:00"
  period_type       = "weekly"
  backup_at         = [1]
}
```

### Panic Output
error message: {"error":{"code":"111400007","message":"The selected cache engine type is not supported.","ext_message":null}}

### Expected Behavior
Create Redis 5.0 of type Master/Standby
Note: Redis cluster is working but not the Master/standby or single instance

### Actual Behavior
Error when create the Master/standby instance

### Steps to Reproduce
1. `terraform apply`

**Comment by ShiChangkuo** [comment]
@achraf2405 the product ID for engine version 5.0 is **redis.cluster.xu1.large.r1.8-h**, also you can get it from the following data source:

```
data "flexibleengine_dcs_product_v1" "product1" {
  engine_version = "4.0;5.0"
  cache_mode     = "single"
}
```

**Comment by achraf2405** [comment]
@ShiChangkuo thank you for you answer, when i choose the product ID **redis.cluster.xu1.large.r1.8-h**  terraform will create a **cluster type redis** and that's working as i mentioned in my first message, but what i need is a **Master/Standby**  or **single instance** and not a cluster. Today only the version 3.0 supports those two instances types.

**Comment by ShiChangkuo** [comment]
@achraf2405 you can replace **cluster** with **single** or **ha** in procust ID.
e.g. redis.single.xu1.large.r1.8-h

**Comment by achraf2405** [comment]
@ShiChangkuo I tried putting **redis.single.xu1.large.r1.8-h** as product ID
and i get this error:
{"error":{"code":"DCS.4927","message":"The param spec_code is invalid","ext_message":null}}

However it works when i put **redis.cluster.xu1.large.r1.64-h**, so today the only supported redis 5.0 instance is of type cluster.

**Comment by achraf2405** [comment]
Hello @ShiChangkuo could you check please?

**Comment by ShiChangkuo** [comment]
@achraf2405 the following product IDs are tesing well:
- redis.ha.xu1.large.r2.1-h  // **Master/Standby** type
- redis.cluster.xu1.large.r2.4-h // **Redis Cluster** type
- redis.proxy.xu1.large.4-h // **Proxy Cluster** type
- redis.single.xu1.large.1-h // **Single-node** type

**Comment by ShiChangkuo** [comment]
I added some arguments in data.flexibleengine_dcs_product_v1, we can get the ID of an available product with the data source.

```hcl
# product of Redis 4.0/5.0 with Proxy Cluster type
data "flexibleengine_dcs_product_v1" "product4" {
  engine         = "redis"
  engine_version = "4.0;5.0"
  cache_mode     = "proxy"
  capacity       = 4
}
```

**Comment by achraf2405** [comment]
Thank you i will test that when the release V1.34.0 is ready :)

**Comment by ShiChangkuo** [comment]
@achraf2405 are there any updates?

**Comment by achraf2405** [comment]
@ShiChangkuo 
yes it's working fine now, thank you :)
