### ISSUE TITLE
[Feature request] Allow differenciate instance class in flexibleengine_rds_flavors_v3 datasource

### ISSUE THREAD

**Issue by MrLuje** [FlexibleEngineCloud/terraform-provider-flexibleengine#817]
flexibleengine_rds_flavors_v3 datasource allows to filter rds flavors based on some criterias
```hcl
data "flexibleengine_rds_flavors_v3" "postgresql_13_single" {
  db_type       = "PostgreSQL"
  db_version    = 13
  instance_mode = "single"
  vcpus         = "2"
  memory        = "4"
}
```
and gives the following output 
```hcl
data "flexibleengine_rds_flavors_v3" "postgresql_13_single" {
    db_type       = "PostgreSQL"
    db_version    = "13"
    flavors       = [
        {
            memory = 4
            mode   = "single"
            name   = "rds.pg.s3.large.2"
            vcpus  = "2"
        },
        {
            memory = 4
            mode   = "single"
            name   = "rds.pg.c6.large.2"
            vcpus  = "2"
        },
    ]
    id            = "flavors"
    instance_mode = "single"
    memory        = 4
    vcpus         = 2
}
```
2 instance classes match my request but there are no more criterias to filter on.

From what I see, one is a "General-enhanced" and the other is a "General-enhanced II"
![image](https://user-images.githubusercontent.com/632075/194557151-ed814db4-98ba-4ab3-bfb6-f125f94e8751.png)

It would be nice to have either :
* an extra parameter on flexibleengine_rds_flavors_v3 datasource to filter on a specific `instance class`
* this information available in the datasource result so we can filter on it

**Comment by ShiChangkuo** [comment]
@MrLuje will add a parameter  named `group_type` to filter RDS flavors by instance class.
