### ISSUE TITLE
Reduce confusing beetween network_id and subnet_id arguments

### ISSUE THREAD

**Issue by gaetanars** [FlexibleEngineCloud/terraform-provider-flexibleengine#857]
@ShiChangkuo I made a little table of the following resources and their attributes :

| Resource                          | Argument             | Subnet or Network ID |
| --------------------------------- | -------------------- | :------------------: |
| apig_instance                    | `subnet_id`           | Network ID           |
| cce_cluster_v3                  | `subnet_id`           | Network ID           |
| cce_node_pool_v3               | `subnet_id`           | Network ID           |
| compute_instance_v2             | `network.UUID`         | Network ID           |
| compute_interface_attach_v2    | `network_id`          | Network ID           |
| cse_microservice_engine         | `network_id`          | Network ID           |
| css_cluster_v1                  | `subnet_id`           | Network ID           |
| dcs_instance_v1                 | `network_id`          | Network ID           |
| dds_instance                     | `subnet_id`           | Network ID           |
| dms_kafka_instance              | `network_id`          | Network ID           |
| drs_job                          | `db_info.subnet_id`  | Network ID           |
| dws_cluster_v1                  | `subnet_id`           | Network ID           |
| fgs_function                     | `network_id`          | Network ID           |
| lb_loadbalancer_v2              | `vip_subnet_id`      | Subnet ID            |
| lb_loadbalancer_v3              | `ipv4_subnet_id`     | Subnet ID            |
| lb_loadbalancer_v3              | `ipv6_network_id`    | Network ID           |
| lb_member_v2                      | `subnet_id`           | Subnet ID           |
| lb_member_v3                      | `subnet_id`           | Subnet ID           |
| mls_instance_v1                 | `subnet_id`           | Network ID           |
| mrs_cluster_v1                  | `subnet_id`           | Network ID           |
| mrs_hybrid_cluster_v1          | `subnet_id`           | Network ID           |
| nat_gateway_v2                  | `subnet_id`           | Network ID           |
| nat_snat_rule_v2               | `subnet_id`           | Network ID           |
| networking_port_v2              | `fixed_ip.subnet_id` | Subnet ID            |
| networking_port_v2              | `network_id`          | Network ID           |
| networking_router_interface_v2 | `subnet_id`           | Subnet ID            |
| networking_subnet_v2            | `network_id`          | Network ID           |
| networking_vip_v2               | `subnet_id`           | Subnet ID            |
| networking_vip_v2               | `network_id`          | Network ID           |
| rds_instance_v3                 | `subnet_id`           | Network ID           |
| sdrs_protectedinstance_v1       | `primary_subnet_id`  | Subnet ID            |
| sfs_turbo                        | `subnet_id`           | Network ID           |
| vpc_eip_associate               | `network_id`          | Network ID           |
| vpcep_endpoint                   | `network_id`          | Network ID           |
| waf_dedicated_instance          | `subnet_id`           | Network ID           |

* **Network ID** : can be a `flexibleengine_networking_network_v2.id` (logical) or a `flexibleengine_vpc_subnet_v1.id` (less logical)
* **Subnet ID**: can be a `flexibleengine_networking_subnet_v2.id`or a `flexibleengine_vpc_subnet_v1.subnet_id`

I understand in #853 that you want to use `subnet_id` argument when user can use `flexibleengine_vpc_subnet_v1.id`, but what happen for the user when he have a `network_id` ?

There is 4 cases where `subnet_id` refer to a real Subnet ID, how to treat this cases ?

What can we do around this to reduce confusing for the users?

**Comment by ShiChangkuo** [comment]
@gaetanars Thanks for the table.

I want to **deprecate** the **networking_network** and **networking_subnet** resources, then users can only get the `subnet_id` from `flexibleengine_vpc_subnet_v1.xxx.id`.

Whether the argument is `subnet_id` or `network_id`, we can use `flexibleengine_vpc_subnet_v1.xxx.id` because they are the same value. 

The following resources are exceptions:
| resource | argument | how to fix |
| --- | --- | --- |
| lb_loadbalancer_v2 | vip_subnet_id | improve the document |
| lb_loadbalancer_v3 | ipv4_subnet_id | improve the document |
| lb_member_v2 |subnet_id | improve the document |
| lb_member_v3 | subnet_id | improve the document |
| networking_port_v2 | fixed_ip.subnet_id | improve the document |
| networking_router_interface_v2 | subnet_id | deprecate the resource |
| networking_vip_v2 | subnet_id | improve the document |
| sdrs_protectedinstance_v1 | primary_subnet_id | improve the document |

To keep compatibility, it is difficult to change the parameter name. It is recommended that we improve the document.

**Comment by gaetanars** [comment]
We can work on document part, but we must accord us on the right terminology to use.
How do we define the `subnet_id` or `network_id` when it refer to `flexibleengine_vpc_subnet_v1.xxx.id` ?
I think this definition is good : *The ID of the VPC Subnet*.

And for the other : *The `subnet_id` of the VPC Subnet*

Are you agree with that ?

**Comment by ShiChangkuo** [comment]
yes, it looks more clear.

**Comment by ShiChangkuo** [comment]
@gaetanars can we close this issue as the documents were updated?

**Comment by gaetanars** [comment]
Yes we can. Thx.
