### ISSUE TITLE
[DDS] Failed to GET resource flexibleengine_dds_databaserole 

### ISSUE THREAD

**Issue by valentin-dubreuil** [FlexibleEngineCloud/terraform-provider-flexibleengine#885]
Same issue as here :  https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/pull/882#issue-1517117471 except it's for the ressource flexibleengine_dds_databaserole and the error code is DBS.200823

### References
- https://github.com/FrangipaneTeam/provider-flexibleengine/issues/28#issue-1512796136

**Comment by azrod** [comment]
@ShiChangkuo Is it possible to have a progress report ?
