### ISSUE TITLE
[RDS] database delete not working for postgresql instance

### ISSUE THREAD

**Issue by dmicheneau** [FlexibleEngineCloud/terraform-provider-flexibleengine#898]
### Terraform Version
Terraform v1.3.7

### Affected Resource(s)
- rds_instance
- rds_database

### Terraform Configuration Files
```hcl
resource "flexibleengine_rds_instance_v3" "example-instance" {
  name              = "example-instance"
  flavor            = var.rds_flavor_id
  availability_zone = [var.primary_az, var.secondary_az]
  security_group_id = flexibleengine_networking_secgroup_v2.secgroup.id
  vpc_id            = var.vpc_id
  subnet_id         = var.subnet_id
  db {
    type     = "PostgreSQL"
    version  = "14"
    password = var.db_password
    port     = "8635"
  }
  volume {
    disk_encryption_id = flexibleengine_kms_key_v1.key.id
    type               = "COMMON"
    size               = 100
  }
  backup_strategy {
    start_time = "08:00-09:00"
    keep_days  = 1
  }
}

resource "flexibleengine_rds_database" "example-database" {
  instance_id = "xxxxxxxxxxxxx"
  name       = "example_database"
  character_set = "utf8"
}

```

### Panic Output
terraform destroy
```
flexibleengine_rds_database.example-database-3: Destroying... [id=e081562bfc1946d59bbc55ed34922c32in03/example_database]
│ Error: error deleting RDS database: {"status_code":403,"request_id":"1bcdfe404d211d80ab413bfa46fa41c6","error_code":"DBS.280343","error_message":"Operation not supported by the DB engine."}
```

### Expected Behavior
Delete the database

### Actual Behavior
Do not delete the database

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a database
2. `terraform destroy`

**Comment by ShiChangkuo** [comment]
@dmicheneau Maybe the RDS instance is backing up, have you tried destroying it later?

**Comment by dmicheneau** [comment]
The backup is done.
And i've the same problem:
![image](https://user-images.githubusercontent.com/47741512/212341636-cbfc53bc-723e-45b1-a41e-11409398c074.png)

date
ven. 13 janv. 2023 15:21:14 CET
 ===> terraform destroy
flexibleengine_rds_database.example-rds-database: Refreshing state... [id=6b5ff3b1415f4696976f960046a2d10ein03/examplerdsdatabase]
╷
│ Error: Instance cannot be destroyed
│ 
│   on main.tf.json line 1, in resource.flexibleengine_rds_database:
│    1: {"provider":{"flexibleengine":{"access_key":"YZEQYAS2UU3YNSCDUIFC","domain_name":"OCB0005592","insecure":false,"region":"eu-west-0","secret_key":"UaClLLY0ZcIHTdjLpfW8W8jnRrZ7RrateeoHq5AN"}},"resource":{"flexibleengine_rds_database":{"example-rds-database":{"character_set":"UTF8","instance_id":"6b5ff3b1415f4696976f960046a2d10ein03","lifecycle":{"prevent_destroy":true},"name":"examplerdsdatabase"}}},"terraform":{"required_providers":{"flexibleengine":{"source":"FlexibleEngineCloud/flexibleengine","version":"1.35.1"}}}}
│ 
│ Resource flexibleengine_rds_database.example-rds-database has lifecycle.prevent_destroy set, but the plan calls for this resource to be destroyed. To avoid this error and continue
│ with the plan, either disable lifecycle.prevent_destroy or reduce the scope of the plan using the -target flag.
╵


TERRAFORM_PROVIDER_VERSION = 1.35.1

**Comment by dmicheneau** [comment]
And i don't see the database in backup file, i see only:
pg_wal 
base

**Comment by ShiChangkuo** [comment]
@dmicheneau I also got the same error in my environment. After checking with the API docs and console, I found that PostgreSQL is not support to delete databases.

I will update the docs in the next release.
