### ISSUE TITLE
In `flexibleengine_swr_organization_users` why use user_id AND user_name?

### ISSUE THREAD

**Issue by gaetanars** [FlexibleEngineCloud/terraform-provider-flexibleengine#904]
Provider 1.36.0

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_swr_organization_users

### Description
In `flexibleengine_swr_organization_users` resource, in `users` block, `user_id` is required and there is also `user_name` that there is optionnal, why use both?

Only required `user_id` is suffisant, no?

**Comment by ShiChangkuo** [comment]
@gaetanars I agree with you, but the [API](https://docs.prod-cloud-ocb.orange-business.com/api/swr/swr_02_0042.html#swr_02_0042__table196185211479) asks both `user_id` and `user_name` are required.

If only `user_id` is required in the provider, we should call the IAM API to query the user_name by id with IAM permissions.

**Comment by gaetanars** [comment]
@ShiChangkuo, [in huaweicloud-provider](https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/9ebfabd04ed8d2a72e1c6a8b3a97f727998f3659/huaweicloud/services/swr/resource_huaweicloud_swr_organization_permissions.go#L119) there is the necessary function to retrieve user_name.

What happens if we pass incorrect couple user_id/user_name ? I don't see any test on that. 

I think that to reduce error risks you can deprecate `user_name`.

**Comment by ShiChangkuo** [comment]
For the account without IAM permissions, there is an error when querying the `user_name`:

```
Error: Error retrieving FlexibleEngine user(46d809e321f142a5aa5f750481f3cXXX):
  Action forbidden: [GET https://iam.eu-west-0.prod-cloud-ocb.orange-business.com/v3.0/OS-USER/users/46d809e321f142a5aa5f750481f3cXXX],
  error message: {"error":{"code":403,"message":"You are not authorized to perform the requested action.","title":"Forbidden"}}
```

**Comment by ShiChangkuo** [comment]
If we pass incorrect couple user_id/user_name, we will get the following error:
```
Error: Error creating FlexibleEngine SWR Organization:
  Bad request with: [POST https://swr-api.eu-west-0.prod-cloud-ocb.orange-business.com/v2/manage/namespaces/demo-00469934/access],
  error message: {"errors":[{"errorCode":"SVCSTG.SWR.4001067","errorMessage":"'username' or 'userID' is invalid","detail":""}]}
```

**Comment by gaetanars** [comment]
Ok so a user without IAM permissions should pass the right couple `user_id`/`user_name`, and a user with IAM permissions can pass only the `user_id`.

Ok for me.
