### ISSUE TITLE
[DMS] Error when import inexistant rocketMQ user

### ISSUE THREAD

**Issue by gaetanars** [FlexibleEngineCloud/terraform-provider-flexibleengine#907]
### Terraform Version
```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/flexibleenginecloud/flexibleengine v1.36.0
```

### Affected Resource(s)
- flexibleengine_dms_rocketmq_user

Terraform doc say that when you read an inexistant resource, provider must return a blank ID to tell Terraform the resource no longer exists (maybe it was destroyed out of band).

When we try to import an inexistant rocketMq User, we have this error : 
`Error: error retrieving DmsRocketMQUser: Bad request with: [GET https://dms.eu-west-0.prod-cloud-ocb.orange-business.com/v2/6f9b3db803e6449e8dce83e566aac41b/instances/2fbb7ef2-a2a9-41ac-83c3-f9a9a9a9239f/users/usertest], error message: {"error_code":"DMS.00500972","error_msg":"The user does not exist."}`

This is because in  [huaweicloud-provider](https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/b98282f1d3a9030549d2fc605f0432564ff33616/huaweicloud/common/common.go#L133) only http 404 are catched, but DMS API seems to respond with another code.

Can you please correct this issue?

**Comment by Jason-Zhang9309** [comment]
This issue should have been resolved as we have updated the reference to huaweicloud.
Please your flexibleengine provider to the latest version.

**Comment by gaetanars** [comment]
You prior must publish a new release :)
