### ISSUE TITLE
[OBS] Can't create public bucket because of policy

### ISSUE THREAD

**Issue by gaetanars** [FlexibleEngineCloud/terraform-provider-flexibleengine#909]
If I want to create a public bucket with this code : 

```
resource "flexibleengine_obs_bucket" "source" {
  bucket        = "my-tf-test-source-bucket"
  acl           = "public-read-write"
  storage_class = "STANDARD"
  region        = "eu-west-0"
} 
```

I see that anonymous user ACLs is `read|write` but Bucket Policy stay `private`.

According to the doc : 
> If an ACL, roles, and a bucket policy are used at the same time and their authorization conflicts, the authorization priorities come as the bucket policy, roles, and the ACL.

It may be interresting to set the bucket policy according to the preset acl.

**Comment by ShiChangkuo** [comment]
@gaetanars Yes, you are right. The priorities was changed.
