### ISSUE TITLE
Resources marked deprecated 

### ISSUE THREAD

**Issue by azrod** [FlexibleEngineCloud/terraform-provider-flexibleengine#914]
The documentations of this resources indicate `deprecated` but the terraform schema does not specify this. 
Please add `Deprecated` in terraform schema

### Affected Resource(s)

- flexibleengine_lb_certificate_v2 ([tf doc](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/lb_certificate_v2)) ([Schema](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/blob/f3d8ef5561d41a0451d8f14d4dd634b1de42dbcc/flexibleengine/resource_flexibleengine_lb_certificate_v2.go#L14))
- flexibleengine_vpc_eip_v1 (no tf doc) ([Schema](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/blob/f3d8ef5561d41a0451d8f14d4dd634b1de42dbcc/flexibleengine/resource_flexibleengine_vpc_eip.go#L17))
- flexibleengine_vpc_route_v2 ([tf doc](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpc_route_v2)) ([Schema](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/blob/f3d8ef5561d41a0451d8f14d4dd634b1de42dbcc/flexibleengine/resource_flexibleengine_vpc_route_v2.go#L15))
- flexibleengine_compute_floatingip_v2 ([tf doc](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/compute_floatingip_v2)) ([Schema](https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/blob/f3d8ef5561d41a0451d8f14d4dd634b1de42dbcc/flexibleengine/resource_flexibleengine_compute_floatingip_v2.go#L15))

### Terraform Version
v1.36.0

**Comment by ShiChangkuo** [comment]
@azrod I will check and fix the differences.

BTW, can you share how to find the differences between doc and schema?

**Comment by azrod** [comment]
For crossplane provider flexibleengine i have create a golang script for comparing the maps beetween terraform provider and crossplane provider and identify if all resources is implemented. This script compare two maps and check in terraform provider if the resource is deprectaed or not. 

After first exec the script i'm returned 4 resources has not implemented. After manual checking i'm found difference beetween the doc and the schema. 

For more information https://github.com/FrangipaneTeam/provider-flexibleengine/pull/153

**Comment by ShiChangkuo** [comment]
@azrod we ca not add  **DeprecationMessage** filed for `flexibleengine_vpc_eip_v1` because both `flexibleengine_vpc_eip_v1` and `flexibleengine_vpc_eip` are defined by **resourceVpcEIPV1**.

other resources are fixed by #919
