### ISSUE TITLE
[CCE] NodePool unused value (typo)

### ISSUE THREAD

**Issue by mydoomfr** [FlexibleEngineCloud/terraform-provider-flexibleengine#915]
### Affected Resource(s)
- flexibleengine_cce_node_pool_v3

There was a typo issue in the nodepool resource, see the old resolved issue https://github.com/FlexibleEngineCloud/terraform-provider-flexibleengine/issues/819

Because the typo is still present in the basecode, this also affects the auto-documentation on the flexible-engine crossplane provider side, see : https://doc.crds.dev/github.com/FrangipaneTeam/provider-flexibleengine/cce.flexibleengine.upbound.io/NodePool/v1beta1@v0.1.2#spec-forProvider-scallEnable

It may be time to delete the variable definition to get a clean basecode and communicate about it as a breaking change in the next major release?

I can create the PR if needed

**Comment by ShiChangkuo** [comment]
@mydoomfr can we add a deprecated message for *scall_enable*, then delete it after two versions？
