### ISSUE TITLE
Tags unavailable on TF resources

### ISSUE THREAD

**Issue by juanacor** [FlexibleEngineCloud/terraform-provider-flexibleengine#923]
Hello, 

For billing purposes we need to tag deployed resources. We can add tags manually using the console but some terraform resources do not support tagging.

### Terraform Version
Terraform v1.3.4 on linux_amd64

### Affected Resource(s)
- [flexibleengine_networking_subnet_v2](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/networking_subnet_v2)
- [flexibleengine_networking_floatingip_v2](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/networking_floatingip_v2)
- [flexibleengine_networking_router_v2](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/networking_router_v2)

Thanks in advance.

**Comment by ShiChangkuo** [comment]
@juanacor The relevant resources in this issue have been deprecated for a long time, please use the following resources:
- [flexibleengine_vpc_subnet_v1](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpc_subnet_v1)
- [flexibleengine_vpc_eip](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpc_eip)
- [flexibleengine_vpc_v1](https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/vpc_v1)

**Comment by juanacor** [comment]
Ok, thank you for your feeback
