### ISSUE TITLE
Image sharing

### ISSUE THREAD

**Issue by sebbbastien** [FlexibleEngineCloud/terraform-provider-flexibleengine#927]
Hi,

Please consider to add support of sharing/accepting private images through Terraform as available on openstack provider:

- [openstack_images_image_access_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/images_image_access_v2)
- [openstack_images_image_access_accept_v2](https://registry.terraform.io/providers/terraform-provider-openstack/openstack/latest/docs/resources/images_image_access_accept_v2)

Best regards,

**Comment by antonin-a** [comment]
@ShiChangkuo @niuzhenguo can you please check this one. 
We need to validate if "access" and "accept" is part of the standard Openstack APIs we are supporting. This is part of Glance (openstack component used for IMS) and the API whitepaper is mentionning "Core APIs" (https://docs.prod-cloud-ocb.orange-business.com/api/wp/wp_01_0003.html). 
If we refer to Flexible Engine API doc it is possible to share (by adding a target tenant as member) but I can't see anyhting related to "accept" (https://docs.prod-cloud-ocb.orange-business.com/api/ims/en-us_topic_0036994317.html)
