### ISSUE TITLE
[CBR] Cannot set both backup policy id and replication id

### ISSUE THREAD

**Issue by thivr** [FlexibleEngineCloud/terraform-provider-flexibleengine#940]
### Terraform Provider Version
1.37.0

### Affected Resource(s)
- flexibleengine_cbr_vault

### Issue
A CBR vault can be associated with a backup policy and a replication policy at the same time. However the provider accepts only one string for policy_id:

https://registry.terraform.io/providers/FlexibleEngineCloud/flexibleengine/latest/docs/resources/cbr_vault#policy_id
 - (Optional, String) Specifies a policy to associate with the CBR vault.

**Comment by ShiChangkuo** [comment]
> A CBR vault can be associated with a backup policy and a replication policy at the same time.

@thivr how do we do this action via console or API? I cannot find it.

**Comment by thivr** [comment]
@ShiChangkuo You can do it using console or API
I did it with the console, using this https://docs.prod-cloud-ocb.orange-business.com/usermanual/cbr/cbr_03_0029.html
With the API, doc is not very detailed bu here we can see that multiple policies can be set at the same time https://docs.prod-cloud-ocb.orange-business.com/api/cbr/AssociateVaultPolicy.html <<< add_policy_ids

**Comment by ShiChangkuo** [comment]
ok, I got it and this feature will be released in v1.39.0

**Comment by thivr** [comment]
@ShiChangkuo sounds good, thanks :-)
