### ISSUE TITLE
flexibleengine_obs_bucket: Access Denied when enabling with a custom KMS

### ISSUE THREAD

**Issue by MrLuje** [FlexibleEngineCloud/terraform-provider-flexibleengine#951]
Hi there,

### Terraform Version
Terraform v1.3.2

### Affected Resource(s)
Please list the resources as a list, for example:
- flexibleengine_obs_bucket
- flexibleengine_kms_key_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    flexibleengine = {
      source  = "FlexibleEngineCloud/flexibleengine"
      version = "1.35.0"
    }
  }
}

provider "flexibleengine" {
  # Configuration options
  access_key  = var.access_key
  secret_key  = var.secret_key
  domain_name = var.domain_name
  region      = "eu-west-0"
  tenant_name = var.tenant_name
}

resource "flexibleengine_kms_key_v1" "kms_s3_pvc_cce_dev-rci" {
  key_alias       = "kms_s3_pvc_cce_dev-rci"
  pending_days    = "7"
  is_enabled      = true
}

resource "flexibleengine_obs_bucket" "backup2" {
  bucket   = "pvc-test"
  multi_az = true

  encryption = true
  kms_key_id = flexibleengine_kms_key_v1.kms_s3_pvc_cce_dev-rci.id
}
```

### Debug Output
```hcl
flexibleengine_obs_bucket.backup2: Creating...
╷
│ Error: failed to enable default encryption of OBS bucket pvc-test: AccessDenied,
│  Reason: Access Denied
│ 
│   with flexibleengine_obs_bucket.backup2,
│   on s3.tf line 16, in resource "flexibleengine_obs_bucket" "backup2":
│   16: resource "flexibleengine_obs_bucket" "backup2" {
│ 
```

### Expected Behavior
Bucket should be created with a given KMS

### Actual Behavior
Bucket creation fails.
If I set `kms_key_id ` to null (eg: use eu-west-0 default OBS keys), it works

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
These resources are not in the default eu-west-0 tenant
These commands are run with an admin account

**Comment by ShiChangkuo** [comment]
it seems that you should allow the OBS can access KMS service.

**Comment by MrLuje** [comment]
Hi @ShiChangkuo, doing the same operation from the console with the same account used in terraform works without any issue

**Comment by ShiChangkuo** [comment]
@MrLuje I tested it well with the same configuration.
I think you can try again in debug mode, then open a service ticket in Orange.

**Comment by MrLuje** [comment]
@ShiChangkuo 
With the help of Orange Support, it is now working with the following steps :
* On the KMS key (`kms_s3_pvc_cce_dev-rci` in my case), you need to grant your own account to use it, being a KMS admin doesn't help
* Add `Describe Key` permission to your user id on the KMS key
* `terraform apply` and it's working

I noticed there is no terraform resource to to grant a KMS key.
Can you confirm if there are enough APIs to add a new resource to the provider ? (I'll open a separate issue to track it)
* https://docs.prod-cloud-ocb.orange-business.com/en-us/api/kms/kms_02_0028.html
* https://docs.prod-cloud-ocb.orange-business.com/en-us/api/kms/kms_02_0029.html
* https://docs.prod-cloud-ocb.orange-business.com/en-us/api/kms/kms_02_0030.html
* https://docs.prod-cloud-ocb.orange-business.com/en-us/api/kms/kms_02_0031.html

**Comment by ShiChangkuo** [comment]
@MrLuje Thanks for your feedback. I can implement a new resource based on the above APIs.
