### ISSUE TITLE
CCE : initial_node_count should not trigger scale down

### ISSUE THREAD

**Issue by gbrd** [FlexibleEngineCloud/terraform-provider-flexibleengine#975]
I use CCE 

I also use the autoscaler.

Here is the scenario  :

- I set initial_node_count to 1 for my node pool in my tarraform config

- later the node pool scales (thanks to autoscaler) to 2 nodes

- if I apply again my terraform script (for any other changes elsewhere unrelated), my node count in my node pool is forced back to 1.

How can I set initial value (required by terraform provider) to 1 by tell it not to be changed later if autoscaler decided to change it.

### Expected Behavior
node_pool not touched (initial_node_count should only be used on creation)

### Actual Behavior
node_pool forced to count = initial_node_count

### Steps to Reproduce
Create a node_pool with initial_node_count=1 via terraform
add some pods to have autoscaler scale it to 2 nodes
run terraform apply again

**Comment by ShiChangkuo** [comment]
Sorry for the delay!

The issue will be fixed in the next release in the next week.

Now, you can add [lifecycle](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle) block in node pool resource as a workaround:

```hcl
resource "flexibleengine_cce_node_pool_v3" "pool" {
  # ...

  lifecycle {
    ignore_changes = [
      initial_node_count,
    ]
  }
}
```
