### ISSUE TITLE
CCE feature request : cluster hibernation

### ISSUE THREAD

**Issue by gbrd** [FlexibleEngineCloud/terraform-provider-flexibleengine#976]
Is it possible to put a cluster in hibernation state  using this terraform provider ? 
https://docs.prod-cloud-ocb.orange-business.com/fr-fr/usermanual2/cce/cce_10_0214.html

**Comment by ShiChangkuo** [comment]
@gbrd thanks for your advise and we will implement this feature at the end of this month.
